/* ============================================================
   bank-eng.js — คลังข้อสอบภาษาอังกฤษ : Past & Future Tenses
   en001–en150 · แท็กหัวข้อ (t) ตรงกับหัวข้อ h2 ใน content-eng.js ทุกข้อ
   ทุกข้อเน้นกับดักที่นักเรียนไทยพลาดจริง เช่น didn't + ช่อง 2 ·
   will ในอนุประโยค when/if · Present Perfect คู่กับคำบอกเวลาอดีต ·
   กริยาบอกสภาวะในรูป continuous
   ============================================================ */
QUIZ_BANKS["eng_main"] = [

/* ---------- 1.1 Past Simple (en001–en012) ---------- */

{ id:"en001", t:"1.1 Past Simple", d:"easy",
  q:"Choose the correct sentence.  (เลือกประโยคที่ถูกต้อง)",
  c:["She went to the market yesterday.","She go to the market yesterday.","She goes to the market yesterday.","She gone to the market yesterday."],
  a:0,
  w:"คำว่า yesterday บอกเวลาในอดีตที่จบไปแล้ว จึงต้องใช้กริยาช่อง 2 ของ go ซึ่งคือ went",
  e:["ถูก — went เป็นช่อง 2 ของ go ตรงกับคำบอกเวลา yesterday",
     "ผิด — go เป็นช่อง 1 ใช้กับปัจจุบันไม่ได้คู่กับ yesterday",
     "ผิด — goes เป็นรูปปัจจุบันของประธานเอกพจน์ ใช้กับอดีตไม่ได้",
     "ผิด — gone เป็นช่อง 3 ต้องมี have/has นำหน้าเสมอ"] },

{ id:"en002", t:"1.1 Past Simple", d:"easy",
  q:"What is the correct question form?  \"____ you finish your homework last night?\"",
  c:["Do","Did","Does","Are"],
  a:1,
  w:"ประโยคคำถามใน Past Simple ใช้ Did + ประธาน + กริยาช่อง 1 เสมอ โดย did เป็นตัวแบกความเป็นอดีตไว้แทน",
  e:["ผิด — Do ใช้กับปัจจุบัน ไม่ตรงกับ last night",
     "ถูก — Did นำหน้าแล้วตามด้วย finish ซึ่งเป็นช่อง 1 ตรงตามโครงสร้าง",
     "ผิด — Does ใช้กับปัจจุบันและประธานเอกพจน์บุรุษที่ 3",
     "ผิด — Are ใช้กับ verb to be ไม่ใช่กริยาแท้อย่าง finish"] },

{ id:"en003", t:"1.1 Past Simple", d:"medium",
  q:"Which sentence is grammatically correct?",
  c:["He didn't went to school.","He doesn't went to school.","He didn't go to school.","He not went to school."],
  a:2,
  w:"เมื่อมี did/didn't อยู่แล้ว กริยาหลักต้องกลับเป็นช่อง 1 เพราะ did แบกความเป็นอดีตไว้แทนแล้ว จะใช้ช่อง 2 ซ้ำอีกไม่ได้",
  e:["ผิด — เป็นกับดักที่พลาดบ่อยที่สุด มี didn't แล้วต้องใช้ go ไม่ใช่ went",
     "ผิด — ผิดสองชั้น ทั้งใช้ doesn't กับอดีต และใช้ went หลัง doesn't",
     "ถูก — didn't + go (ช่อง 1) ถูกต้องตามโครงสร้างปฏิเสธของ Past Simple",
     "ผิด — กริยาแท้ต้องใช้ did ช่วยในรูปปฏิเสธ จะเติม not เฉย ๆ ไม่ได้"] },

{ id:"en004", t:"1.1 Past Simple", d:"easy",
  q:"Which time expression goes with the Past Simple?",
  c:["tomorrow","next week","at the moment","two days ago"],
  a:3,
  w:"Past Simple ใช้กับเวลาที่จบไปแล้วในอดีต เช่น yesterday, last night, in 2015, two days ago, when I was young",
  e:["ผิด — tomorrow บอกอนาคต",
     "ผิด — next week บอกอนาคต",
     "ผิด — at the moment บอกปัจจุบันขณะนี้ คู่กับ Present Continuous",
     "ถูก — ago บอกเวลาที่ผ่านมาแล้ว จึงคู่กับ Past Simple"] },

{ id:"en005", t:"1.1 Past Simple", d:"medium",
  q:"Complete the sentence: \"They ____ dinner at seven o'clock last night and then watched a movie.\"",
  c:["had","have","has","having"],
  a:0,
  w:"ทั้งประโยคเล่าเหตุการณ์ที่จบแล้วในอดีต และมี watched ซึ่งเป็นช่อง 2 อยู่ในประโยคเดียวกัน กริยาตัวแรกจึงต้องเป็นช่อง 2 เช่นกันคือ had",
  e:["ถูก — had เป็นช่อง 2 ของ have และขนานกับ watched ที่ตามมา",
     "ผิด — have เป็นช่อง 1 ไม่เข้ากับ last night",
     "ผิด — has เป็นรูปปัจจุบันของประธานเอกพจน์ ทั้งยังไม่ตรงกับ They",
     "ผิด — having เป็นรูป -ing ต้องมีกริยาช่วยนำหน้า"] },

{ id:"en006", t:"1.1 Past Simple", d:"hard",
  q:"Which sentence uses the Past Simple correctly?",
  c:["I was study English for three hours yesterday.","I studied English for three hours yesterday.","I did studied English for three hours yesterday.","I am studied English for three hours yesterday."],
  a:1,
  w:"ประโยคบอกเล่าใน Past Simple ใช้กริยาช่อง 2 ตัวเดียวโดยไม่ต้องมี did หรือ verb to be ช่วย",
  e:["ผิด — was + study ผิดโครงสร้าง ถ้าจะใช้ was ต้องตามด้วย studying",
     "ถูก — studied เป็นช่อง 2 ของ study ใช้เดี่ยว ๆ ในประโยคบอกเล่าได้เลย",
     "ผิด — did ใช้ในประโยคคำถามและปฏิเสธ ถ้าใช้ในประโยคบอกเล่าเพื่อเน้น กริยาต้องเป็นช่อง 1 (did study)",
     "ผิด — am เป็นปัจจุบัน และ am + studied เป็นรูป passive ที่ไม่ถูกความหมายในที่นี้"] },

{ id:"en007", t:"1.1 Past Simple", d:"medium",
  q:"Choose the correct negative sentence.",
  c:["She not was happy with the result.","She didn't was happy with the result.","She wasn't happy with the result.","She doesn't happy with the result."],
  a:2,
  w:"เมื่อกริยาแท้คือ verb to be (was/were) ให้เติม not ที่ตัว be ได้เลย ไม่ต้องใช้ did ช่วย",
  e:["ผิด — ต้องเรียงเป็น was not ไม่ใช่ not was",
     "ผิด — verb to be ไม่ใช้ did ช่วย",
     "ถูก — was + not = wasn't ใช้กับประธานเอกพจน์ในอดีตได้ถูกต้อง",
     "ผิด — ผิดทั้งกาล (doesn't เป็นปัจจุบัน) และขาด verb to be"] },

{ id:"en008", t:"1.1 Past Simple", d:"easy",
  q:"What is the past form of \"buy\"?",
  c:["buyed","buys","buying","bought"],
  a:3,
  w:"buy เป็นกริยาอปกติ (irregular verb) ช่อง 2 คือ bought ไม่ได้เติม -ed ตามกฎปกติ",
  e:["ผิด — buyed ไม่มีในภาษาอังกฤษ เพราะ buy เป็นกริยาอปกติ",
     "ผิด — buys เป็นรูปปัจจุบันของประธานเอกพจน์",
     "ผิด — buying เป็นรูป -ing",
     "ถูก — buy – bought – bought"] },

{ id:"en009", t:"1.1 Past Simple", d:"hard",
  q:"\"My grandfather ____ in Chiang Mai for forty years, but he moved to Bangkok in 2010.\"  Choose the best answer.",
  c:["lived","has lived","lives","is living"],
  a:0,
  w:"ช่วงเวลาสี่สิบปีนั้นจบลงแล้วเมื่อเขาย้ายออกในปี 2010 จึงเป็นอดีตที่ปิดแล้ว ต้องใช้ Past Simple ไม่ใช่ Present Perfect",
  e:["ถูก — เหตุการณ์จบสิ้นในอดีตพร้อมจุดจบชัดเจน จึงใช้ lived",
     "ผิด — has lived ใช้เมื่อการอยู่ยังต่อเนื่องถึงปัจจุบัน แต่ประโยคบอกว่าย้ายออกไปแล้ว",
     "ผิด — lives เป็นปัจจุบัน ขัดกับ moved ที่บอกว่าย้ายไปแล้ว",
     "ผิด — is living บอกสิ่งที่กำลังเกิดขึ้นตอนนี้ ขัดกับเนื้อความ"] },

{ id:"en010", t:"1.1 Past Simple", d:"medium",
  q:"Which sentence correctly reports a finished past action?",
  c:["We have visited the temple last Sunday.","We visited the temple last Sunday.","We are visiting the temple last Sunday.","We will visit the temple last Sunday."],
  a:1,
  w:"เมื่อมีคำบอกเวลาอดีตที่ชัดเจนอย่าง last Sunday ต้องใช้ Past Simple ห้ามใช้ Present Perfect คู่กัน",
  e:["ผิด — Present Perfect ใช้กับคำบอกเวลาอดีตที่ระบุชัดไม่ได้",
     "ถูก — visited + last Sunday เข้าคู่กันถูกต้อง",
     "ผิด — are visiting เป็นปัจจุบัน ขัดกับ last Sunday",
     "ผิด — will visit เป็นอนาคต ขัดกับ last Sunday"] },

{ id:"en011", t:"1.1 Past Simple", d:"easy",
  q:"Fill in the blank: \"____ she call you yesterday?\"",
  c:["Does","Was","Did","Has"],
  a:2,
  w:"call เป็นกริยาแท้ คำถามในอดีตจึงใช้ Did นำหน้า แล้วตามด้วยกริยาช่อง 1",
  e:["ผิด — Does เป็นปัจจุบัน ขัดกับ yesterday",
     "ผิด — Was ใช้กับ verb to be หรือรูป -ing ไม่ใช่ call เปล่า ๆ",
     "ถูก — Did she call …? ถูกต้องตามโครงสร้าง",
     "ผิด — Has ต้องตามด้วยกริยาช่อง 3 และใช้กับ Present Perfect"] },

{ id:"en012", t:"1.1 Past Simple", d:"hard",
  q:"Which sentence shows a past habit or repeated action correctly?",
  c:["When I was a child, I walk to school every day.","When I was a child, I am walking to school every day.","When I am a child, I walked to school every day.","When I was a child, I walked to school every day."],
  a:3,
  w:"Past Simple ใช้เล่านิสัยหรือสิ่งที่ทำซ้ำ ๆ ในอดีตได้ด้วย โดยกริยาทั้งสองส่วนของประโยคต้องเป็นอดีตให้สอดคล้องกัน",
  e:["ผิด — was เป็นอดีตแต่ walk เป็นปัจจุบัน กาลไม่สอดคล้องกัน",
     "ผิด — am walking เป็นปัจจุบันกำลังทำ ขัดกับเนื้อความที่เล่าอดีต",
     "ผิด — am เป็นปัจจุบัน ขัดกับ walked ที่เป็นอดีต",
     "ถูก — was และ walked เป็นอดีตทั้งคู่ สื่อความว่าเคยทำเป็นประจำตอนเด็ก"] },


/* ---------- 1.2 Past Continuous (en013–en023) ---------- */

{ id:"en013", t:"1.2 Past Continuous", d:"easy",
  q:"What is the structure of the Past Continuous?",
  c:["was/were + verb-ing","did + verb 1","have/has + verb 3","will + verb 1"],
  a:0,
  w:"Past Continuous ใช้โครงสร้าง was (เอกพจน์) หรือ were (พหูพจน์) ตามด้วยกริยาเติม -ing เพื่อบอกสิ่งที่กำลังดำเนินอยู่ ณ จุดหนึ่งในอดีต",
  e:["ถูก — เช่น I was reading · They were playing",
     "ผิด — did + verb 1 เป็นโครงสร้างคำถามและปฏิเสธของ Past Simple",
     "ผิด — have/has + verb 3 เป็น Present Perfect",
     "ผิด — will + verb 1 เป็น Future Simple"] },

{ id:"en014", t:"1.2 Past Continuous", d:"easy",
  q:"Complete the sentence: \"At eight o'clock last night, I ____ TV.\"",
  c:["watch","was watching","watched","have watched"],
  a:1,
  w:"at eight o'clock last night เป็นจุดเวลาหนึ่งในอดีต และประโยคต้องการสื่อว่ากำลังทำอยู่ ณ จุดนั้น จึงใช้ Past Continuous",
  e:["ผิด — watch เป็นช่อง 1 ใช้กับปัจจุบัน",
     "ถูก — was watching เน้นภาพว่ากำลังดูอยู่พอดีตอนสองทุ่ม",
     "ผิด — watched บอกว่าดูจบแล้ว ไม่ได้เน้นว่ากำลังดำเนินอยู่ ณ เวลานั้น",
     "ผิด — have watched เป็น Present Perfect ใช้กับเวลาอดีตที่ระบุชัดไม่ได้"] },

{ id:"en015", t:"1.2 Past Continuous", d:"medium",
  q:"Choose the correct Past Continuous sentence.",
  c:["They was playing football.","They were play football.","They were playing football.","They was play football."],
  a:2,
  w:"They เป็นพหูพจน์จึงต้องใช้ were และกริยาต้องเติม -ing เป็น playing",
  e:["ผิด — They ต้องใช้ were ไม่ใช่ was",
     "ผิด — หลัง were ต้องเป็น playing ไม่ใช่ play",
     "ถูก — were + playing ถูกทั้งการเลือก be และรูป -ing",
     "ผิด — ผิดทั้งสองจุด ทั้ง was และ play"] },

{ id:"en016", t:"1.2 Past Continuous", d:"easy",
  q:"Which use of the Past Continuous is correct?",
  c:["บอกเหตุการณ์สั้น ๆ ที่จบไปแล้ว","บอกแผนการในอนาคต","บอกประสบการณ์ที่เคยทำมาถึงปัจจุบัน","บอกฉากหลังหรือสิ่งที่กำลังดำเนินอยู่ในอดีต"],
  a:3,
  w:"หน้าที่หลักของ Past Continuous คือวาดฉากหลังของเรื่อง หรือบอกว่า ณ เวลานั้นมีอะไรกำลังดำเนินอยู่ แล้วมักมีเหตุการณ์สั้น ๆ มาแทรก",
  e:["ผิด — เหตุการณ์สั้นที่จบไปแล้วใช้ Past Simple",
     "ผิด — แผนอนาคตใช้รูปอนาคต ไม่ใช่ Past Continuous",
     "ผิด — ประสบการณ์ที่ต่อเนื่องถึงปัจจุบันใช้ Present Perfect",
     "ถูก — เช่น It was raining and the wind was blowing hard."] },

{ id:"en017", t:"1.2 Past Continuous", d:"hard",
  q:"Which sentence is NOT acceptable?",
  c:["I was knowing the answer.","I was thinking about you.","I was cooking dinner.","I was waiting for the bus."],
  a:0,
  w:"กริยาบอกสภาวะ (stative verbs) เช่น know, believe, belong, own มักไม่ใช้ในรูป continuous เพราะไม่ได้บรรยายการกระทำที่กำลังดำเนินอยู่",
  e:["ถูก — เป็นข้อที่ใช้ไม่ได้ ต้องพูดว่า I knew the answer.",
     "ผิด — ข้อนี้ใช้ได้ เพราะ think ในความหมายว่าครุ่นคิดถือเป็นการกระทำ",
     "ผิด — ข้อนี้ใช้ได้ cook เป็นกริยาแสดงการกระทำตามปกติ",
     "ผิด — ข้อนี้ใช้ได้ wait เป็นกริยาแสดงการกระทำที่กินเวลา"] },

{ id:"en018", t:"1.2 Past Continuous", d:"medium",
  q:"Complete: \"____ they working when you arrived?\"",
  c:["Was","Were","Did","Are"],
  a:1,
  w:"คำถามใน Past Continuous ใช้ was/were ขึ้นต้นตามจำนวนของประธาน ในที่นี้ they เป็นพหูพจน์จึงใช้ Were",
  e:["ผิด — Was ใช้กับประธานเอกพจน์",
     "ถูก — Were they working …? ถูกต้องทั้งรูป be และประธาน",
     "ผิด — Did ต้องตามด้วยกริยาช่อง 1 ไม่ใช่ working",
     "ผิด — Are เป็นปัจจุบัน ขัดกับ arrived ที่เป็นอดีต"] },

{ id:"en019", t:"1.2 Past Continuous", d:"easy",
  q:"Which sentence best shows two LONG actions in progress at the same moment in the past?",
  c:["I cooked while she cleaned the house.","I cook while she is cleaning the house.","I was cooking while she was cleaning the house.","I will cook while she cleans the house."],
  a:2,
  w:"เมื่อสองเหตุการณ์ยาวดำเนินไปพร้อมกันในอดีต นิยมใช้ Past Continuous ทั้งสองฝั่ง โดยมี while เชื่อม",
  e:["ผิด — ถูกไวยากรณ์ แต่เป็น Past Simple ทั้งคู่ จึงไม่ได้วาดภาพว่าทั้งสองกำลังดำเนินอยู่",
     "ผิด — กาลไม่สอดคล้องกันและเป็นปัจจุบัน",
     "ถูก — was cooking / was cleaning วาดภาพสองเหตุการณ์ที่ทับซ้อนกันได้ชัดที่สุด",
     "ผิด — เป็นอนาคต ไม่ตรงกับโจทย์ที่ถามถึงอดีต"] },

{ id:"en020", t:"1.2 Past Continuous", d:"hard",
  q:"\"I ____ my keys while I ____ for my phone.\"  Choose the best pair.",
  c:["was finding / was looking","was finding / looked","found / looked","found / was looking"],
  a:3,
  w:"find เป็นเหตุการณ์ชั่วขณะที่เกิดแวบเดียวจึงใช้ Past Simple ส่วน look for เป็นการกระทำที่กินเวลาและเป็นฉากหลัง จึงใช้ Past Continuous",
  e:["ผิด — find เป็นเหตุการณ์แวบเดียว ไม่เหมาะกับรูป continuous",
     "ผิด — สลับกัน ทำให้เหตุการณ์สั้นกลายเป็นยาวและเหตุการณ์ยาวกลายเป็นสั้น",
     "ผิด — ใช้ Past Simple ทั้งคู่ ทำให้ไม่เห็นภาพว่าอันหนึ่งเป็นฉากหลัง",
     "ถูก — found (สั้น) แทรกเข้ามาระหว่าง was looking (ยาว) ซึ่งเป็นรูปแบบคลาสสิกของบทนี้"] },

{ id:"en021", t:"1.2 Past Continuous", d:"medium",
  q:"Which sentence correctly uses the Past Continuous in the negative?",
  c:["He wasn't listening to me.","He didn't listening to me.","He not was listening to me.","He doesn't listening to me."],
  a:0,
  w:"รูปปฏิเสธของ Past Continuous คือ was/were + not + verb-ing โดยไม่ต้องใช้ did ช่วย",
  e:["ถูก — wasn't listening ถูกต้องตามโครงสร้าง",
     "ผิด — เมื่อใช้ didn't กริยาต้องเป็นช่อง 1 คือ listen",
     "ผิด — ต้องเรียงเป็น was not ไม่ใช่ not was",
     "ผิด — doesn't เป็นปัจจุบัน และโครงสร้างผิด"] },

{ id:"en022", t:"1.2 Past Continuous", d:"medium",
  q:"What does this sentence emphasize?  \"She was writing a letter all evening.\"",
  c:["การเขียนจบสมบูรณ์แล้ว","การเขียนดำเนินไปตลอดช่วงเย็น โดยไม่บอกว่าจบหรือไม่","การเขียนจะเกิดขึ้นในอนาคต","การเขียนเกิดขึ้นครั้งเดียวแวบเดียว"],
  a:1,
  w:"Past Continuous เน้นความต่อเนื่องของการกระทำในช่วงเวลาหนึ่ง โดยไม่ได้บอกว่าการกระทำนั้นเสร็จสิ้นหรือไม่",
  e:["ผิด — ถ้าจะบอกว่าเขียนจบต้องใช้ She wrote a letter.",
     "ถูก — จุดเด่นของรูปนี้คือความต่อเนื่อง ไม่ใช่ความสำเร็จ",
     "ผิด — was writing เป็นอดีต ไม่ใช่อนาคต",
     "ผิด — รูป continuous สื่อความยาวนาน ตรงข้ามกับเหตุการณ์แวบเดียว"] },

{ id:"en023", t:"1.2 Past Continuous", d:"easy",
  q:"Choose the correct form: \"The children ____ in the garden at five o'clock.\"",
  c:["was playing","is playing","were playing","play"],
  a:2,
  w:"children เป็นพหูพจน์ (รูปพหูพจน์อปกติของ child) จึงต้องใช้ were",
  e:["ผิด — children เป็นพหูพจน์ จึงใช้ was ไม่ได้",
     "ผิด — is เป็นปัจจุบันและเป็นเอกพจน์",
     "ถูก — were playing ถูกทั้งความสอดคล้องของประธานและรูปกาล",
     "ผิด — play ไม่ได้บอกว่ากำลังดำเนินอยู่ ณ เวลานั้น"] },


/* ---------- 1.3 Past Simple vs. Past Continuous (en024–en036) ---------- */

{ id:"en024", t:"1.3 Past Simple vs. Past Continuous", d:"easy",
  q:"\"I ____ a shower when the phone ____.\"  Choose the best pair.",
  c:["took / was ringing","was taking / was ringing","took / rang","was taking / rang"],
  a:3,
  w:"เหตุการณ์ยาวที่เป็นฉากหลังใช้ Past Continuous ส่วนเหตุการณ์สั้นที่แทรกเข้ามาใช้ Past Simple",
  e:["ผิด — สลับกัน การอาบน้ำเป็นฉากหลัง ส่วนเสียงโทรศัพท์คือเหตุการณ์แทรก",
     "ผิด — ใช้ continuous ทั้งคู่ ทำให้ความหมายเป็นสองเหตุการณ์ยาวคู่ขนาน ซึ่งไม่ตรงกับเสียงโทรศัพท์ที่ดังแวบเดียว",
     "ผิด — ใช้ Past Simple ทั้งคู่ ทำให้ความหมายกลายเป็นทำสองอย่างต่อกัน",
     "ถูก — was taking (ยาว) ถูกขัดจังหวะโดย rang (สั้น)"] },

{ id:"en025", t:"1.3 Past Simple vs. Past Continuous", d:"hard",
  q:"Which word usually introduces the LONG action (the background)?",
  c:["while","when","because","after"],
  a:0,
  w:"while มักตามด้วยเหตุการณ์ยาวในรูป Past Continuous ส่วน when มักตามด้วยเหตุการณ์สั้นในรูป Past Simple",
  e:["ถูก — while + was/were + verb-ing เป็นรูปแบบที่พบบ่อยที่สุด",
     "ผิด — when มักนำหน้าเหตุการณ์สั้นที่แทรกเข้ามา",
     "ผิด — because บอกเหตุผล ไม่ได้บอกความยาวของเหตุการณ์",
     "ผิด — after บอกลำดับก่อนหลัง ไม่ได้บอกความยาว"] },

{ id:"en026", t:"1.3 Past Simple vs. Past Continuous", d:"medium",
  q:"\"While she ____ dinner, her brother ____ home.\"",
  c:["cooked / was coming","was cooking / came","cooked / came","was cooking / was coming"],
  a:1,
  w:"หลัง while ใช้เหตุการณ์ยาวคือ was cooking ส่วนการกลับถึงบ้านเป็นเหตุการณ์แวบเดียวจึงใช้ came",
  e:["ผิด — สลับกัน ทำให้การทำอาหารกลายเป็นเหตุการณ์สั้น",
     "ถูก — ตรงกับรูปแบบ while + long action, short action",
     "ผิด — ใช้ Past Simple ทั้งคู่ ซึ่งไม่เข้ากับ while ที่ต้องการฉากหลัง",
     "ผิด — come เป็นเหตุการณ์แวบเดียว ไม่เหมาะกับรูป continuous ในบริบทนี้"] },

{ id:"en027", t:"1.3 Past Simple vs. Past Continuous", d:"hard",
  q:"What is the difference in meaning?  (ก) When I arrived, she cooked dinner.  (ข) When I arrived, she was cooking dinner.",
  c:["ความหมายเหมือนกันทุกประการ","(ก) เธอทำอาหารอยู่ก่อนแล้ว · (ข) เธอเริ่มทำหลังฉันมาถึง","(ก) เธอเริ่มทำอาหารหลังจากฉันมาถึง · (ข) เธอทำอาหารอยู่ก่อนแล้วตอนฉันมาถึง","ทั้งสองประโยคผิดไวยากรณ์"],
  a:2,
  w:"Past Simple สองตัวติดกันสื่อว่าเกิดต่อกันตามลำดับ ส่วน Past Continuous สื่อว่าเหตุการณ์นั้นดำเนินอยู่ก่อนแล้วและยังดำเนินต่อ",
  e:["ผิด — ความหมายต่างกันชัดเจน เป็นจุดที่ออกสอบบ่อย",
     "ผิด — สลับความหมายของทั้งสองประโยค",
     "ถูก — ลำดับเหตุการณ์ต่างกันโดยสิ้นเชิงแม้จะเปลี่ยนแค่รูปกริยา",
     "ผิด — ทั้งสองประโยคถูกไวยากรณ์ เพียงแต่สื่อความต่างกัน"] },

{ id:"en028", t:"1.3 Past Simple vs. Past Continuous", d:"medium",
  q:"\"The lights ____ out while we ____ the film.\"",
  c:["were going / were watching","were going / watched","went / watched","went / were watching"],
  a:3,
  w:"ไฟดับเป็นเหตุการณ์แวบเดียวจึงใช้ Past Simple ส่วนการดูหนังเป็นฉากหลังยาว ๆ ที่มี while นำหน้า จึงใช้ Past Continuous",
  e:["ผิด — ไฟดับเกิดขึ้นทันที ไม่เหมาะกับรูป continuous",
     "ผิด — สลับกัน ไฟดับไม่ใช่เหตุการณ์ที่กินเวลา",
     "ผิด — while ต้องการฉากหลังที่เป็นรูป continuous",
     "ถูก — went (สั้น) แทรกเข้ามาระหว่าง were watching (ยาว)"] },

{ id:"en029", t:"1.3 Past Simple vs. Past Continuous", d:"easy",
  q:"Which sentence shows a sequence of finished actions?",
  c:["I got up, brushed my teeth, and ate breakfast.","I was getting up, was brushing my teeth, and was eating breakfast.","I got up, was brushing my teeth, and ate breakfast.","I was getting up, brushed my teeth, and was eating breakfast."],
  a:0,
  w:"เมื่อเล่าเหตุการณ์หลายอย่างที่เกิดต่อกันเป็นลำดับและจบไปแล้ว ใช้ Past Simple ทั้งหมดจึงเหมาะที่สุด",
  e:["ถูก — Past Simple เรียงต่อกันสื่อลำดับก่อนหลังได้ชัดที่สุด",
     "ผิด — รูป continuous ทั้งชุดสื่อว่าทั้งสามอย่างกำลังทำพร้อมกัน ซึ่งไม่สมเหตุสมผล",
     "ผิด — กาลปนกันโดยไม่มีเหตุผล ทำให้ลำดับสับสน",
     "ผิด — กาลปนกันเช่นกัน และไม่สื่อลำดับที่ชัดเจน"] },

{ id:"en030", t:"1.3 Past Simple vs. Past Continuous", d:"hard",
  q:"\"I ____ to tell you, but you ____ on the phone.\"  (ฉันพยายามจะบอกคุณอยู่ครั้งหนึ่ง แต่ตอนนั้นคุณกำลังคุยโทรศัพท์อยู่)",
  c:["was trying / were talking","tried / were talking","tried / talked","was trying / talked"],
  a:1,
  w:"การพยายามบอกเป็นความตั้งใจที่เกิดขึ้นเป็นครั้ง ๆ จึงใช้ Past Simple ส่วนการคุยโทรศัพท์เป็นสภาพที่กำลังดำเนินอยู่ตอนนั้น จึงใช้ Past Continuous ซึ่งอธิบายว่าทำไมบอกไม่ได้",
  e:["ผิด — ทำให้การพยายามกลายเป็นฉากหลัง ซึ่งขัดกับเหตุผลของประโยคที่ว่าติดตรงที่อีกฝ่ายไม่ว่าง",
     "ถูก — tried (การกระทำที่เกิดขึ้น) ขัดกับ were talking (สภาพที่เป็นอยู่ตอนนั้น)",
     "ผิด — ใช้ Past Simple ทั้งคู่ ทำให้ไม่เห็นว่าการคุยโทรศัพท์เป็นสภาพที่ขวางอยู่",
     "ผิด — สลับบทบาทของทั้งสองเหตุการณ์"] },

{ id:"en031", t:"1.3 Past Simple vs. Past Continuous", d:"medium",
  q:"Which sentence pattern is most common in storytelling?",
  c:["ใช้ Past Simple ทั้งเรื่องโดยไม่มีฉากหลังเลย","ใช้ Present Simple เล่าเรื่องในอดีต","ใช้ Past Continuous วางฉากหลัง แล้วใช้ Past Simple เล่าเหตุการณ์ที่เกิดขึ้น","ใช้ Future Simple เล่าเรื่องในอดีต"],
  a:2,
  w:"การเล่าเรื่องมักเปิดฉากด้วย Past Continuous เพื่อบอกบรรยากาศ แล้วใช้ Past Simple เดินเรื่องต่อ เช่น It was raining when he opened the door.",
  e:["ผิด — เรื่องเล่าที่ไม่มีฉากหลังจะแบนและขาดบรรยากาศ",
     "ผิด — Present Simple ใช้เล่าอดีตได้ในบางสไตล์ แต่ไม่ใช่รูปแบบมาตรฐานที่ข้อสอบถาม",
     "ถูก — เป็นโครงสร้างมาตรฐานของการเล่าเรื่องในภาษาอังกฤษ",
     "ผิด — Future Simple ใช้เล่าอดีตไม่ได้"] },

{ id:"en032", t:"1.3 Past Simple vs. Past Continuous", d:"medium",
  q:"\"It ____ heavily when we ____ the house.\"  (ตอนที่เราออกจากบ้าน ฝนกำลังตกหนักอยู่)",
  c:["rained / were leaving","was raining / were leaving","rained / left","was raining / left"],
  a:3,
  w:"ฝนตกเป็นสภาพแวดล้อมที่ดำเนินอยู่จึงใช้ Past Continuous ส่วนการออกจากบ้านเป็นจุดเวลาหนึ่งจึงใช้ Past Simple",
  e:["ผิด — สลับกัน การออกจากบ้านไม่ใช่ฉากหลัง",
     "ผิด — ใช้ continuous ทั้งคู่ ทำให้ไม่มีจุดเวลาอ้างอิงที่ชัดเจน",
     "ผิด — ใช้ Past Simple ทั้งคู่ ทำให้ไม่เห็นภาพบรรยากาศ",
     "ถูก — was raining เป็นฉากหลัง และ left เป็นจุดเวลาที่อ้างอิง"] },

{ id:"en033", t:"1.3 Past Simple vs. Past Continuous", d:"hard",
  q:"Which sentence misuses \"while\"?",
  c:["While my phone rang, I was studying.","When my phone rang, I was studying.","While I was studying, my phone rang.","I was studying when my phone rang."],
  a:0,
  w:"while ควรตามด้วยเหตุการณ์ยาวในรูป continuous เสียงโทรศัพท์ดังเป็นเหตุการณ์แวบเดียว จึงควรใช้ when แทน",
  e:["ถูก — เป็นข้อที่ผิด เพราะใช้ while กับเหตุการณ์แวบเดียว",
     "ผิด — ข้อนี้ถูกต้อง when ตามด้วยเหตุการณ์สั้น",
     "ผิด — ข้อนี้ถูกต้อง while ตามด้วยเหตุการณ์ยาว",
     "ผิด — ข้อนี้ถูกต้อง สลับลำดับอนุประโยคได้โดยความหมายไม่เปลี่ยน"] },

{ id:"en034", t:"1.3 Past Simple vs. Past Continuous", d:"medium",
  q:"\"What ____ you ____ when the teacher came in?\"",
  c:["did / do","were / doing","did / doing","was / do"],
  a:1,
  w:"คำถามที่ถามว่ากำลังทำอะไรอยู่ ณ จังหวะที่มีเหตุการณ์แทรก ใช้ Past Continuous คือ were + doing",
  e:["ผิด — did/do ถามถึงการกระทำที่จบแล้ว ไม่ได้ถามว่ากำลังทำอะไรอยู่",
     "ถูก — What were you doing …? เป็นรูปคำถามมาตรฐานของ Past Continuous",
     "ผิด — did ต้องตามด้วยกริยาช่อง 1 ไม่ใช่ doing",
     "ผิด — you ต้องใช้ were และหลัง be ต้องเป็น doing"] },

{ id:"en035", t:"1.3 Past Simple vs. Past Continuous", d:"easy",
  q:"In the pattern \"long action + short action\", which tense marks the SHORT action?",
  c:["Present Perfect","Past Continuous","Past Simple","Future Simple"],
  a:2,
  w:"เหตุการณ์สั้นที่แทรกเข้ามากลางเหตุการณ์ยาว ใช้ Past Simple ส่วนเหตุการณ์ยาวใช้ Past Continuous",
  e:["ผิด — Present Perfect ไม่ใช้ในรูปแบบนี้",
     "ผิด — Past Continuous ใช้กับเหตุการณ์ยาวที่เป็นฉากหลัง",
     "ถูก — เช่น the phone rang, the lights went out, he came in",
     "ผิด — Future Simple เป็นอนาคต ไม่เกี่ยวกับรูปแบบนี้"] },

{ id:"en036", t:"1.3 Past Simple vs. Past Continuous", d:"hard",
  q:"\"When the fire alarm ____, the students ____ their exam.\"  Which pair fits a story where the exam was interrupted?",
  c:["was going off / took","was going off / were taking","went off / took","went off / were taking"],
  a:3,
  w:"เสียงสัญญาณดังเป็นเหตุการณ์แวบเดียวจึงใช้ Past Simple ส่วนการสอบเป็นกิจกรรมยาวที่ดำเนินอยู่ก่อนแล้วและถูกขัดจังหวะ จึงใช้ Past Continuous",
  e:["ผิด — สลับกัน ทำให้การสอบกลายเป็นเหตุการณ์แวบเดียว",
     "ผิด — สัญญาณเตือนไม่ใช่เหตุการณ์ที่กินเวลาในบริบทนี้",
     "ผิด — ใช้ Past Simple ทั้งคู่ ทำให้อ่านได้ว่าสัญญาณดังก่อนแล้วนักเรียนจึงเริ่มสอบ",
     "ถูก — went off (สั้น) ตัดเข้ามาระหว่าง were taking (ยาว) ซึ่งตรงกับคำว่า interrupted"] },


/* ---------- 1.4 กริยาช่อง 2 และกฎการเติม (en037–en047) ---------- */

{ id:"en037", t:"1.4 กริยาช่อง 2 และกฎการเติม", d:"easy",
  q:"What is the past form of \"stop\"?",
  c:["stopped","stoped","stopt","stoping"],
  a:0,
  w:"คำพยางค์เดียวที่ลงท้ายด้วยสระตัวเดียวตามด้วยพยัญชนะตัวเดียว ต้องเบิ้ลพยัญชนะท้ายก่อนเติม -ed จึงเป็น stopped",
  e:["ถูก — stop → stopped ตามกฎเบิ้ลพยัญชนะท้าย",
     "ผิด — ขาดการเบิ้ลตัว p",
     "ผิด — ไม่มีรูปนี้ในภาษาอังกฤษ",
     "ผิด — stoping สะกดผิด และเป็นรูป -ing ไม่ใช่ช่อง 2"] },

{ id:"en038", t:"1.4 กริยาช่อง 2 และกฎการเติม", d:"easy",
  q:"What is the past form of \"study\"?",
  c:["studyed","studied","studed","studying"],
  a:1,
  w:"คำที่ลงท้ายด้วยพยัญชนะ + y ต้องเปลี่ยน y เป็น i ก่อนเติม -ed จึงเป็น studied",
  e:["ผิด — ต้องเปลี่ยน y เป็น i ก่อน",
     "ถูก — stud + i + ed = studied",
     "ผิด — สะกดผิด ตัดตัวอักษรหายไป",
     "ผิด — เป็นรูป -ing ไม่ใช่ช่อง 2"] },

{ id:"en039", t:"1.4 กริยาช่อง 2 และกฎการเติม", d:"medium",
  q:"Which verb does NOT double its final consonant before -ed?",
  c:["plan","stop","visit","drop"],
  a:2,
  w:"visit มีสองพยางค์และเน้นเสียงที่พยางค์แรก จึงไม่ต้องเบิ้ลพยัญชนะท้าย เขียนเป็น visited",
  e:["ผิด — plan → planned ต้องเบิ้ล",
     "ผิด — stop → stopped ต้องเบิ้ล",
     "ถูก — visit → visited ไม่ต้องเบิ้ล เพราะไม่ได้ลงเสียงหนักที่พยางค์ท้าย",
     "ผิด — drop → dropped ต้องเบิ้ล"] },

{ id:"en040", t:"1.4 กริยาช่อง 2 และกฎการเติม", d:"medium",
  q:"Which verb ends in -y but does NOT change y to i?",
  c:["carry","try","study","play"],
  a:3,
  w:"ถ้าหน้า y เป็นสระ (เช่น a, o) ให้เติม -ed ได้เลย ไม่ต้องเปลี่ยน y เป็น i จึงเป็น played",
  e:["ผิด — carry → carried เพราะหน้า y เป็นพยัญชนะ",
     "ผิด — try → tried เพราะหน้า y เป็นพยัญชนะ",
     "ผิด — study → studied เพราะหน้า y เป็นพยัญชนะ",
     "ถูก — play → played เพราะหน้า y เป็นสระ a"] },

{ id:"en041", t:"1.4 กริยาช่อง 2 และกฎการเติม", d:"easy",
  q:"What is the past form of \"go\"?",
  c:["went","gone","goed","going"],
  a:0,
  w:"go เป็นกริยาอปกติ ช่อง 2 คือ went และช่อง 3 คือ gone",
  e:["ถูก — go – went – gone",
     "ผิด — gone เป็นช่อง 3 ต้องใช้กับ have/has",
     "ผิด — ไม่มีรูปนี้ เพราะ go เป็นกริยาอปกติ",
     "ผิด — going เป็นรูป -ing"] },

{ id:"en042", t:"1.4 กริยาช่อง 2 และกฎการเติม", d:"hard",
  q:"Which group contains ONLY irregular past forms?",
  c:["walked, played, watched","took, wrote, drank","opened, closed, wanted","cleaned, helped, listened"],
  a:1,
  w:"กริยาอปกติไม่ได้เติม -ed แต่เปลี่ยนรูปไปเลย เช่น take–took, write–wrote, drink–drank",
  e:["ผิด — ทั้งสามตัวเติม -ed จึงเป็นกริยาปกติ",
     "ถูก — ทั้งสามตัวเปลี่ยนรูปโดยไม่เติม -ed",
     "ผิด — ทั้งสามตัวเติม -ed",
     "ผิด — ทั้งสามตัวเติม -ed"] },

{ id:"en043", t:"1.4 กริยาช่อง 2 และกฎการเติม", d:"medium",
  q:"What is the past form of \"cut\"?",
  c:["cutted","cutted up","cut","cuted"],
  a:2,
  w:"cut เป็นกริยาที่รูปช่อง 1 ช่อง 2 และช่อง 3 เหมือนกันหมด กลุ่มนี้ยังมี put, let, hit, set, cost, hurt",
  e:["ผิด — ไม่มีรูปนี้ในภาษาอังกฤษ",
     "ผิด — เป็นวลีที่ไม่ถูกต้องในบริบทนี้",
     "ถูก — cut – cut – cut ต้องดูบริบทเวลาเพื่อรู้ว่าเป็นช่องไหน",
     "ผิด — สะกดผิดและไม่มีรูปนี้"] },

{ id:"en044", t:"1.4 กริยาช่อง 2 และกฎการเติม", d:"easy",
  q:"What is the past form of \"like\"?",
  c:["likeed","liking","likd","liked"],
  a:3,
  w:"คำที่ลงท้ายด้วย e อยู่แล้ว เติมเพียง -d ตัวเดียว จึงเป็น liked",
  e:["ผิด — เติม e ซ้ำโดยไม่จำเป็น",
     "ผิด — เป็นรูป -ing",
     "ผิด — สะกดผิด ต้องคง e ไว้",
     "ถูก — like + d = liked"] },

{ id:"en045", t:"1.4 กริยาช่อง 2 และกฎการเติม", d:"hard",
  q:"Which sentence contains a WRONG past form?",
  c:["They catched the bus at seven.","She brought her lunch to school.","He taught us English last year.","We built a sandcastle on the beach."],
  a:0,
  w:"catch เป็นกริยาอปกติ ช่อง 2 คือ caught ไม่ใช่ catched",
  e:["ถูก — เป็นข้อที่ผิด ต้องเป็น caught the bus",
     "ผิด — bring → brought ถูกต้อง",
     "ผิด — teach → taught ถูกต้อง",
     "ผิด — build → built ถูกต้อง"] },

{ id:"en046", t:"1.4 กริยาช่อง 2 และกฎการเติม", d:"medium",
  q:"Which pair of past forms is correct?",
  c:["think – thinked","choose – chose","teach – teached","bring – bringed"],
  a:1,
  w:"choose เป็นกริยาอปกติ ช่อง 2 คือ chose ส่วนอีกสามตัวเขียนเป็นรูปเติม -ed ซึ่งผิดทั้งหมด",
  e:["ผิด — ต้องเป็น think – thought",
     "ถูก — choose – chose – chosen",
     "ผิด — ต้องเป็น teach – taught",
     "ผิด — ต้องเป็น bring – brought"] },

{ id:"en047", t:"1.4 กริยาช่อง 2 และกฎการเติม", d:"medium",
  q:"Which verb follows the rule \"double the final consonant\" correctly?",
  c:["open → openned","listen → listenned","prefer → preferred","visit → visitted"],
  a:2,
  w:"กฎเบิ้ลพยัญชนะใช้เมื่อคำนั้นลงเสียงหนักที่พยางค์สุดท้ายและลงท้ายด้วยสระตัวเดียว + พยัญชนะตัวเดียว prefer ลงเสียงหนักที่พยางค์หลัง จึงเป็น preferred",
  e:["ผิด — open ลงเสียงหนักพยางค์แรก จึงเป็น opened",
     "ผิด — listen ลงเสียงหนักพยางค์แรก จึงเป็น listened",
     "ถูก — prefer ลงเสียงหนักพยางค์ท้าย จึงเบิ้ล r เป็น preferred",
     "ผิด — visit ลงเสียงหนักพยางค์แรก จึงเป็น visited"] },


/* ---------- 2.1 เลือกรูปอนาคตให้ตรงเจตนา (en048–en057) ---------- */

{ id:"en048", t:"2.1 เลือกรูปอนาคตให้ตรงเจตนา", d:"easy",
  q:"You decide something at the moment of speaking. Which form do you use?",
  c:["Present Simple","be going to","Present Continuous","will"],
  a:3,
  w:"will ใช้กับการตัดสินใจทันทีตอนพูด เช่น เห็นแก้วหล่นแล้วพูดว่า I'll help you.",
  e:["ผิด — Present Simple ใช้กับตารางเวลาที่ตายตัว",
     "ผิด — be going to ใช้กับสิ่งที่ตั้งใจไว้ก่อนหน้านี้แล้ว",
     "ผิด — Present Continuous ใช้กับนัดหมายที่จัดการเรียบร้อยแล้ว",
     "ถูก — การตัดสินใจเดี๋ยวนั้นเป็นหน้าที่เฉพาะของ will"] },

{ id:"en049", t:"2.1 เลือกรูปอนาคตให้ตรงเจตนา", d:"easy",
  q:"You planned something before now. Which form fits best?",
  c:["be going to","will","Past Simple","Present Perfect"],
  a:0,
  w:"be going to ใช้กับความตั้งใจที่มีอยู่ก่อนแล้ว เช่น I'm going to study medicine next year. ซึ่งวางแผนไว้นานแล้ว",
  e:["ถูก — be going to สื่อว่าคิดไว้ก่อนแล้ว แม้ยังไม่ได้จัดการอะไรเป็นรูปธรรม",
     "ผิด — will สื่อว่าเพิ่งตัดสินใจตอนนี้",
     "ผิด — Past Simple เป็นอดีต",
     "ผิด — Present Perfect เชื่อมอดีตกับปัจจุบัน ไม่ได้บอกอนาคต"] },

{ id:"en050", t:"2.1 เลือกรูปอนาคตให้ตรงเจตนา", d:"hard",
  q:"You already booked a table at a restaurant for tonight. Which is most natural?",
  c:["I will have dinner at Sara's tonight.","I am having dinner at Sara's tonight.","I have dinner at Sara's tonight.","I had dinner at Sara's tonight."],
  a:1,
  w:"Present Continuous ใช้กับนัดหมายที่จัดการเรียบร้อยแล้ว มีเวลา สถานที่ และคู่นัดชัดเจน การจองโต๊ะเข้าเงื่อนไขนี้พอดี",
  e:["ผิด — will ฟังดูเหมือนเพิ่งตัดสินใจ ไม่สะท้อนว่าจองไว้แล้ว",
     "ถูก — เป็นรูปที่เจ้าของภาษาใช้กับนัดหมายส่วนตัวที่ล็อกแล้ว",
     "ผิด — Present Simple ใช้กับตารางเวลาสาธารณะ ไม่ใช่นัดส่วนตัว",
     "ผิด — เป็นอดีต ขัดกับ tonight ที่ยังมาไม่ถึง"] },

{ id:"en051", t:"2.1 เลือกรูปอนาคตให้ตรงเจตนา", d:"medium",
  q:"The train leaves at 6:30 every morning. Which form is used for timetables?",
  c:["will leave","is going to leave","leaves","is leaving"],
  a:2,
  w:"Present Simple ใช้กับตารางเวลาที่ตายตัว เช่น รถไฟ เครื่องบิน ภาพยนตร์รอบฉาย และตารางเรียน",
  e:["ผิด — will ใช้กับการคาดการณ์หรือตัดสินใจ ไม่ใช่ตารางเวลาทางการ",
     "ผิด — be going to ใช้กับความตั้งใจส่วนบุคคล",
     "ถูก — The train leaves at 6:30. เป็นรูปมาตรฐานของตารางเวลา",
     "ผิด — Present Continuous ใช้กับนัดหมายส่วนตัว ไม่ใช่ตารางเดินรถ"] },

{ id:"en052", t:"2.1 เลือกรูปอนาคตให้ตรงเจตนา", d:"hard",
  q:"Look at those black clouds. Which sentence is most appropriate?",
  c:["It will rain.","It rained.","It rains.","It is going to rain."],
  a:3,
  w:"เมื่อมีหลักฐานที่มองเห็นได้ตรงหน้าและชี้ชัดว่ากำลังจะเกิด ใช้ be going to จึงเหมาะกว่า will ที่ใช้กับการคาดเดาลอย ๆ",
  e:["ผิด — will ใช้เมื่อคาดเดาจากความคิดเห็นหรือความเชื่อ ไม่ได้อิงหลักฐานตรงหน้า",
     "ผิด — เป็นอดีต ไม่ตรงกับสถานการณ์ที่กำลังจะเกิด",
     "ผิด — Present Simple ใช้บอกความจริงทั่วไปหรือตารางเวลา",
     "ถูก — เมฆดำคือหลักฐานที่มองเห็นได้ จึงเข้าเงื่อนไขของ be going to พอดี"] },

{ id:"en053", t:"2.1 เลือกรูปอนาคตให้ตรงเจตนา", d:"medium",
  q:"\"The phone is ringing. I ____ it.\"  Choose the best answer.",
  c:["will answer","answer","am going to answer","answered"],
  a:0,
  w:"เสียงโทรศัพท์ดังขึ้นตอนนี้แล้วเพิ่งตัดสินใจจะรับ เป็นการตัดสินใจทันทีจึงใช้ will",
  e:["ถูก — I'll answer it. เป็นการตัดสินใจ ณ วินาทีที่พูด",
     "ผิด — Present Simple ไม่ได้สื่อความตั้งใจในอนาคต",
     "ผิด — be going to สื่อว่าตั้งใจไว้ก่อนแล้ว ซึ่งเป็นไปไม่ได้เพราะโทรศัพท์เพิ่งดัง",
     "ผิด — เป็นอดีต ขัดกับสถานการณ์ที่กำลังเกิดขึ้น"] },

{ id:"en054", t:"2.1 เลือกรูปอนาคตให้ตรงเจตนา", d:"hard",
  q:"Which sentence best expresses a promise?",
  c:["I am going to help you, I promise.","I will help you, I promise.","I help you, I promise.","I am helping you, I promise."],
  a:1,
  w:"will ใช้แสดงคำสัญญา คำเสนอตัวช่วย และการปฏิเสธที่หนักแน่น ซึ่งเป็นหน้าที่เชิงเจตนาที่ be going to ไม่ครอบคลุม",
  e:["ผิด — be going to สื่อความตั้งใจ แต่ไม่ได้ให้น้ำหนักของคำสัญญาเท่า will",
     "ถูก — I will help you เป็นรูปมาตรฐานของการให้สัญญา",
     "ผิด — Present Simple ไม่ได้สื่ออนาคตในบริบทนี้",
     "ผิด — Present Continuous ใช้กับนัดหมาย ไม่ใช่คำสัญญา"] },

{ id:"en055", t:"2.1 เลือกรูปอนาคตให้ตรงเจตนา", d:"easy",
  q:"Which form is used for a personal arrangement that is already fixed?",
  c:["Present Simple","Past Simple","Present Continuous","Past Continuous"],
  a:2,
  w:"Present Continuous เพื่ออนาคตใช้กับนัดหมายส่วนตัวที่จัดการเรียบร้อยแล้ว เช่น I'm meeting the dentist at three.",
  e:["ผิด — Present Simple ใช้กับตารางเวลาสาธารณะที่ตายตัว",
     "ผิด — Past Simple เป็นอดีต",
     "ถูก — ต้องมีเวลาและรายละเอียดชัดเจน ไม่ใช่แค่คิดไว้เฉย ๆ",
     "ผิด — Past Continuous เป็นอดีต"] },

{ id:"en056", t:"2.1 เลือกรูปอนาคตให้ตรงเจตนา", d:"medium",
  q:"What is the main difference between \"I will study medicine\" and \"I am going to study medicine\"?",
  c:["ประโยคแรกเป็นอดีต ประโยคหลังเป็นอนาคต","ความหมายเหมือนกันทุกประการ","ประโยคแรกถูก ประโยคหลังผิดไวยากรณ์","ประโยคแรกฟังเหมือนเพิ่งตัดสินใจหรือเป็นการคาดการณ์ ส่วนประโยคหลังสื่อว่าตั้งใจไว้ก่อนแล้ว"],
  a:3,
  w:"ทั้งคู่เป็นอนาคตและถูกไวยากรณ์ทั้งคู่ แต่ต่างกันที่เจตนา will เน้นการตัดสินใจ ณ ตอนนั้นหรือการคาดการณ์ ส่วน be going to เน้นแผนที่มีอยู่ก่อน",
  e:["ผิด — ทั้งสองประโยคเป็นอนาคตทั้งคู่",
     "ผิด — สื่อเจตนาต่างกันชัดเจน",
     "ผิด — ทั้งสองประโยคถูกไวยากรณ์",
     "ถูก — ความต่างอยู่ที่เจตนาของผู้พูด ไม่ใช่ความถูกผิดทางไวยากรณ์"] },

{ id:"en057", t:"2.1 เลือกรูปอนาคตให้ตรงเจตนา", d:"hard",
  q:"\"A: We don't have any milk.  B: Really? I ____ some on my way home.\"",
  c:["will buy","buy","am buying","bought"],
  a:0,
  w:"B เพิ่งรู้ว่านมหมดตอนที่ A บอก จึงเป็นการตัดสินใจทันทีตอนพูด ต้องใช้ will",
  e:["ถูก — คำว่า Really? บอกชัดว่าเพิ่งรู้และเพิ่งตัดสินใจ",
     "ผิด — Present Simple ไม่สื่อความตั้งใจในอนาคต",
     "ผิด — Present Continuous ต้องเป็นนัดที่จัดการไว้ก่อนแล้ว แต่ B เพิ่งรู้เรื่องนี้",
     "ผิด — เป็นอดีต ขัดกับเนื้อความที่ยังไม่ได้ซื้อ"] },


/* ---------- 2.2 Future Simple — will (en058–en068) ---------- */

{ id:"en058", t:"2.2 Future Simple — will", d:"easy",
  q:"What is the correct structure of the Future Simple?",
  c:["will + verb 2","will + verb 1","will + verb-ing","will + to + verb"],
  a:1,
  w:"Future Simple ใช้ will ตามด้วยกริยาช่อง 1 เสมอ ไม่ว่าประธานจะเป็นอะไร",
  e:["ผิด — หลัง will ต้องเป็นช่อง 1 ไม่ใช่ช่อง 2",
     "ถูก — เช่น I will go · She will go · They will go",
     "ผิด — จะเป็นรูป -ing ได้ต้องเป็น will be + verb-ing ซึ่งคือ Future Continuous",
     "ผิด — หลัง will ไม่มี to"] },

{ id:"en059", t:"2.2 Future Simple — will", d:"easy",
  q:"Which sentence is correct?",
  c:["She wills come tomorrow.","She will comes tomorrow.","She will come tomorrow.","She will to come tomorrow."],
  a:2,
  w:"will ไม่เปลี่ยนรูปตามประธาน และกริยาที่ตามมาต้องเป็นช่อง 1 รูปเปล่า ๆ",
  e:["ผิด — will ไม่เติม s ตามประธานเอกพจน์",
     "ผิด — กริยาหลัง will ไม่เติม s",
     "ถูก — will + come ถูกต้องครบทั้งสองจุด",
     "ผิด — หลัง will ไม่ต้องมี to"] },

{ id:"en060", t:"2.2 Future Simple — will", d:"easy",
  q:"What is the negative form of \"will\"?",
  c:["willn't","not will","don't will","won't"],
  a:3,
  w:"รูปย่อของ will not คือ won't ซึ่งเป็นรูปพิเศษที่ไม่ตรงตามแบบแผนทั่วไป",
  e:["ผิด — ไม่มีรูปนี้ในภาษาอังกฤษ",
     "ผิด — ลำดับคำผิด ต้องเป็น will not",
     "ผิด — will เป็นกริยาช่วยอยู่แล้ว จึงไม่ต้องใช้ do ช่วยซ้ำ",
     "ถูก — will not ย่อเป็น won't"] },

{ id:"en061", t:"2.2 Future Simple — will", d:"hard",
  q:"Which sentence uses \"will\" for a prediction based on opinion?",
  c:["I think it will be sunny tomorrow.","Look at the sky — it is going to rain.","The bus leaves at six.","I am meeting John at five."],
  a:0,
  w:"will ใช้กับการคาดการณ์ที่มาจากความคิดเห็นหรือความเชื่อ มักมาคู่กับ I think, I believe, probably, maybe",
  e:["ถูก — I think เป็นสัญญาณชัดเจนว่าเป็นการคาดเดาจากความคิดเห็น",
     "ผิด — เป็นการคาดการณ์จากหลักฐานที่มองเห็น จึงใช้ be going to",
     "ผิด — เป็นตารางเวลา จึงใช้ Present Simple",
     "ผิด — เป็นนัดหมายส่วนตัว จึงใช้ Present Continuous"] },

{ id:"en062", t:"2.2 Future Simple — will", d:"hard",
  q:"Which sentence shows \"will\" used for an instant refusal?",
  c:["I am not going to start the car.","The car won't start this morning.","The car didn't start this morning.","The car is not starting this morning."],
  a:1,
  w:"won't ใช้แสดงการปฏิเสธที่หนักแน่น รวมถึงกับสิ่งของที่ไม่ยอมทำงาน เช่น The door won't open.",
  e:["ผิด — สื่อความตั้งใจของผู้พูด ไม่ใช่การที่รถไม่ยอมทำงาน",
     "ถูก — เป็นการใช้ won't ในความหมายว่าไม่ยอมสตาร์ท ซึ่งเป็นสำนวนมาตรฐาน",
     "ผิด — เป็นการรายงานอดีตธรรมดา ไม่ได้สื่อความไม่ยอม",
     "ผิด — รูป continuous ไม่สื่อความหมายเชิงปฏิเสธที่หนักแน่น"] },

{ id:"en063", t:"2.2 Future Simple — will", d:"easy",
  q:"Complete: \"I ____ call you when I arrive.\"",
  c:["wills","willing","will","am will"],
  a:2,
  w:"will เป็นกริยาช่วยที่ใช้รูปเดียวกับทุกประธาน และไม่ต้องมี verb to be นำหน้า",
  e:["ผิด — will ไม่เติม s",
     "ผิด — willing เป็นคำคุณศัพท์แปลว่าเต็มใจ ไม่ใช่กริยาช่วย",
     "ถูก — I will call you ถูกต้องตามโครงสร้าง",
     "ผิด — will ไม่ใช้คู่กับ verb to be"] },

{ id:"en064", t:"2.2 Future Simple — will", d:"medium",
  q:"Which sentence offers help?",
  c:["I am going to carry that bag for you.","I carried that bag for you.","I carry that bag for you.","I will carry that bag for you."],
  a:3,
  w:"will ใช้เสนอความช่วยเหลือ ณ ขณะนั้น เช่น เห็นคนถือของหนักแล้วพูดว่า I'll carry it for you.",
  e:["ผิด — be going to สื่อว่าตั้งใจไว้ก่อน ซึ่งไม่เข้ากับการเสนอตัวเดี๋ยวนั้น",
     "ผิด — เป็นอดีต ไม่ใช่การเสนอตัว",
     "ผิด — Present Simple ไม่สื่อการเสนอตัวในอนาคต",
     "ถูก — เป็นรูปมาตรฐานของการเสนอตัวช่วยเหลือ"] },

{ id:"en065", t:"2.2 Future Simple — will", d:"hard",
  q:"Which sentence misuses \"will\" in a time clause?",
  c:["I will go home after the class will end.","I will go home after the class ends.","When I finish, I will call you.","If it rains, we will stay home."],
  a:0,
  w:"ในอนุประโยคที่ขึ้นต้นด้วย when, after, before, if, as soon as ต้องใช้ Present Simple ห้ามใช้ will แม้ความหมายจะเป็นอนาคต",
  e:["ถูก — เป็นข้อที่ผิด เพราะใส่ will ในอนุประโยคหลัง after",
     "ผิด — ข้อนี้ถูกต้อง ends เป็น Present Simple ในอนุประโยค",
     "ผิด — ข้อนี้ถูกต้อง finish เป็น Present Simple หลัง when",
     "ผิด — ข้อนี้ถูกต้อง rains เป็น Present Simple หลัง if"] },

{ id:"en066", t:"2.2 Future Simple — will", d:"medium",
  q:"Complete the question: \"____ you help me with this?\"",
  c:["Do","Will","Are","Did"],
  a:1,
  w:"คำถามใน Future Simple ใช้ Will นำหน้าประธาน แล้วตามด้วยกริยาช่อง 1 และยังใช้เป็นการขอร้องอย่างสุภาพได้ด้วย",
  e:["ผิด — Do ใช้กับปัจจุบัน ไม่สื่ออนาคต",
     "ถูก — Will you help me …? เป็นทั้งคำถามอนาคตและคำขอร้อง",
     "ผิด — Are ต้องตามด้วยรูป -ing หรือคำคุณศัพท์",
     "ผิด — Did เป็นอดีต"] },

{ id:"en067", t:"2.2 Future Simple — will", d:"medium",
  q:"Which word often signals the use of \"will\" for prediction?",
  c:["already","yesterday","probably","just now"],
  a:2,
  w:"คำอย่าง probably, perhaps, maybe, I think, I'm sure มักปรากฏคู่กับ will เพราะเป็นการคาดการณ์ที่ไม่แน่นอน",
  e:["ผิด — already มักใช้กับ Present Perfect",
     "ผิด — yesterday เป็นคำบอกอดีต",
     "ถูก — probably บอกความไม่แน่นอน จึงเข้าคู่กับ will",
     "ผิด — just now ใช้กับเหตุการณ์ที่เพิ่งเกิดในอดีตอันใกล้"] },

{ id:"en068", t:"2.2 Future Simple — will", d:"hard",
  q:"\"I'm sure she ____ the exam. She has studied very hard.\"",
  c:["passes","is passing","passed","will pass"],
  a:3,
  w:"I'm sure บอกว่าเป็นการคาดการณ์ด้วยความเชื่อมั่นของผู้พูด ซึ่งเป็นหน้าที่ของ will",
  e:["ผิด — Present Simple บอกความจริงทั่วไป ไม่ใช่การคาดการณ์",
     "ผิด — Present Continuous ต้องเป็นนัดหมายที่จัดการแล้ว ไม่ใช่ผลสอบ",
     "ผิด — เป็นอดีต แต่ประโยคกำลังพูดถึงการสอบที่ยังไม่เกิด",
     "ถูก — will pass เป็นการคาดการณ์ที่อิงความมั่นใจของผู้พูด"] },


/* ---------- 2.3 be going to (en069–en079) ---------- */

{ id:"en069", t:"2.3 be going to", d:"easy",
  q:"What is the structure of \"be going to\"?",
  c:["am/is/are + going to + verb 1","am/is/are + going to + verb-ing","will + going to + verb 1","have + going to + verb 3"],
  a:0,
  w:"โครงสร้างคือ verb to be (am/is/are) + going to + กริยาช่อง 1 โดย be ต้องผันตามประธาน",
  e:["ถูก — เช่น I am going to travel · She is going to travel",
     "ผิด — หลัง going to ต้องเป็นช่อง 1 ไม่ใช่รูป -ing",
     "ผิด — will กับ be going to ใช้ซ้อนกันไม่ได้",
     "ผิด — ไม่มีโครงสร้างนี้"] },

{ id:"en070", t:"2.3 be going to", d:"easy",
  q:"Choose the correct \"be going to\" sentence.",
  c:["He is going to studies abroad.","He is going to study abroad.","He going to study abroad.","He is go to study abroad."],
  a:1,
  w:"หลัง going to ต้องเป็นกริยาช่อง 1 รูปเปล่า และห้ามละ verb to be",
  e:["ผิด — กริยาหลัง going to ไม่เติม s",
     "ถูก — is going to study ถูกต้องครบทุกส่วน",
     "ผิด — ขาด is ซึ่งเป็น verb to be ที่จำเป็น",
     "ผิด — ต้องเป็น going to ไม่ใช่ go to"] },

{ id:"en071", t:"2.3 be going to", d:"easy",
  q:"When do we prefer \"be going to\" over \"will\"?",
  c:["เมื่อเพิ่งตัดสินใจตอนพูด","เมื่อให้คำสัญญา","เมื่อตั้งใจไว้ก่อนแล้ว หรือมีหลักฐานตรงหน้าที่ชี้ชัด","เมื่อพูดถึงตารางเวลารถไฟ"],
  a:2,
  w:"be going to มีสองหน้าที่หลักคือแสดงความตั้งใจที่มีอยู่ก่อนแล้ว และคาดการณ์จากหลักฐานที่มองเห็นได้",
  e:["ผิด — การตัดสินใจทันทีใช้ will",
     "ผิด — คำสัญญาใช้ will",
     "ถูก — เป็นสองหน้าที่ที่แยก be going to ออกจาก will ได้ชัดที่สุด",
     "ผิด — ตารางเวลาใช้ Present Simple"] },

{ id:"en072", t:"2.3 be going to", d:"hard",
  q:"\"She has bought the tickets. She ____ to Japan next month.\"",
  c:["will travel","travelled","travels","is going to travel"],
  a:3,
  w:"การซื้อตั๋วไว้แล้วแสดงว่ามีแผนมาก่อน จึงใช้ be going to ซึ่งเป็นรูปของความตั้งใจที่เตรียมไว้",
  e:["ผิด — will ฟังเหมือนเพิ่งตัดสินใจ ซึ่งขัดกับการที่ซื้อตั๋วไปแล้ว",
     "ผิด — เป็นอดีต ขัดกับ next month",
     "ผิด — Present Simple ใช้กับตารางเวลาสาธารณะ ไม่ใช่แผนส่วนตัว",
     "ถูก — หลักฐานคือตั๋วที่ซื้อแล้ว ยืนยันว่าเป็นแผนที่วางไว้ล่วงหน้า"] },

{ id:"en073", t:"2.3 be going to", d:"hard",
  q:"Which sentence uses \"be going to\" for a prediction based on present evidence?",
  c:["He is driving too fast — he is going to crash.","I am going to visit my aunt next week.","We are going to have a party on Saturday.","They are going to move to a new house."],
  a:0,
  w:"เมื่อมีหลักฐานที่มองเห็นอยู่ตรงหน้าและนำไปสู่ผลอย่างชัดเจน ใช้ be going to ในความหมายคาดการณ์ ไม่ใช่ความตั้งใจ",
  e:["ถูก — การขับเร็วเกินไปคือหลักฐานตรงหน้าที่ชี้ว่าจะชน",
     "ผิด — เป็นความตั้งใจที่วางแผนไว้ ไม่ใช่การคาดการณ์จากหลักฐาน",
     "ผิด — เป็นแผนการจัดงาน ซึ่งเป็นความตั้งใจ",
     "ผิด — เป็นแผนย้ายบ้าน ซึ่งเป็นความตั้งใจ"] },

{ id:"en074", t:"2.3 be going to", d:"medium",
  q:"What is the negative form?  \"They ____ come to the party.\"",
  c:["do not going to","are not going to","not are going to","will not going to"],
  a:1,
  w:"รูปปฏิเสธเติม not หลัง verb to be เป็น am/is/are + not + going to + verb 1",
  e:["ผิด — verb to be ไม่ใช้ do ช่วย",
     "ถูก — are not going to come ถูกต้องตามโครงสร้าง",
     "ผิด — ลำดับคำผิด ต้องเป็น are not",
     "ผิด — will กับ be going to ใช้ซ้อนกันไม่ได้"] },

{ id:"en075", t:"2.3 be going to", d:"easy",
  q:"Complete the question: \"____ you going to join us tonight?\"",
  c:["Will","Do","Are","Did"],
  a:2,
  w:"คำถามของ be going to ใช้ verb to be ขึ้นต้น ในที่นี้ประธานคือ you จึงใช้ Are",
  e:["ผิด — Will จะใช้ก็ต่อเมื่อไม่มี going to ตามมา",
     "ผิด — be going to ไม่ใช้ do ช่วย",
     "ถูก — Are you going to join …? ถูกต้องตามโครงสร้าง",
     "ผิด — Did เป็นอดีต และไม่ใช้กับ going to"] },

{ id:"en076", t:"2.3 be going to", d:"medium",
  q:"Which sentence sounds most natural for an intention decided long ago?",
  c:["I will become a doctor. I have wanted this since I was six.","I became a doctor. I have wanted this since I was six.","I become a doctor. I have wanted this since I was six.","I am going to become a doctor. I have wanted this since I was six."],
  a:3,
  w:"ประโยคที่สองบอกชัดว่าตั้งใจมาตั้งแต่เด็ก จึงเข้ากับ be going to ที่สื่อแผนซึ่งมีอยู่ก่อนแล้ว",
  e:["ผิด — will ขัดกับข้อมูลที่ว่าตั้งใจมานานแล้ว",
     "ผิด — เป็นอดีต ขัดกับความหมายว่ายังไม่ได้เป็น",
     "ผิด — Present Simple ไม่สื่อเจตนาในอนาคต",
     "ถูก — be going to สะท้อนความตั้งใจที่มีมาก่อนหน้านี้ได้ตรงที่สุด"] },

{ id:"en077", t:"2.3 be going to", d:"hard",
  q:"\"A: Why are you carrying that ladder?  B: I ____ the ceiling light.\"",
  c:["am going to fix","will fix","fix","fixed"],
  a:0,
  w:"การถือบันไดมาแล้วแสดงว่าเตรียมการไว้ก่อน จึงเป็นความตั้งใจที่มีอยู่ก่อน ต้องใช้ be going to",
  e:["ถูก — บันไดในมือคือหลักฐานว่าวางแผนไว้ก่อนถูกถาม",
     "ผิด — will สื่อว่าเพิ่งคิดได้ตอนนี้ ซึ่งขัดกับการที่ถือบันไดมาแล้ว",
     "ผิด — Present Simple ไม่สื่อความตั้งใจในอนาคต",
     "ผิด — เป็นอดีต แต่งานยังไม่ได้ทำ"] },

{ id:"en078", t:"2.3 be going to", d:"medium",
  q:"Which is the correct short form?",
  c:["I'm gonna study — เป็นรูปเขียนทางการที่ใช้ในข้อสอบได้","I'm going to study — ใช้ได้ทั้งพูดและเขียน","I'm go to study — ใช้ได้ในภาษาพูด","I going to study — ใช้ได้เมื่อรีบ"],
  a:1,
  w:"gonna เป็นรูปพูดแบบไม่เป็นทางการ ใช้ในข้อสอบหรืองานเขียนไม่ได้ ส่วน going to ใช้ได้ทุกบริบท",
  e:["ผิด — gonna ใช้ในภาษาพูดเท่านั้น ไม่ควรเขียนในข้อสอบ",
     "ถูก — going to เป็นรูปมาตรฐานที่ปลอดภัยทั้งพูดและเขียน",
     "ผิด — go to ไม่ใช่โครงสร้างนี้",
     "ผิด — ละ verb to be ไม่ได้ในทุกกรณี"] },

{ id:"en079", t:"2.3 be going to", d:"hard",
  q:"Which sentence pair shows the correct contrast?",
  c:["Evidence: I will rain. / Plan: It is going to rain.","Evidence: It rains. / Plan: It rained.","Evidence: Look, it is going to rain. / Sudden decision: OK, I will take an umbrella.","Both forms mean exactly the same thing in every context."],
  a:2,
  w:"be going to ใช้กับการคาดการณ์จากหลักฐานที่มองเห็น ส่วน will ใช้กับการตัดสินใจทันทีที่เกิดขึ้นตามมา",
  e:["ผิด — สลับหน้าที่ของทั้งสองรูป และประโยคแรกผิดไวยากรณ์",
     "ผิด — เป็นรูปปัจจุบันและอดีต ไม่เกี่ยวกับการเทียบนี้",
     "ถูก — เห็นเมฆจึงใช้ going to ส่วนการตัดสินใจหยิบร่มเดี๋ยวนั้นใช้ will",
     "ผิด — ทั้งสองรูปสื่อเจตนาต่างกันในหลายบริบท"] },


/* ---------- 2.4 Present Continuous และ Present Simple เพื่ออนาคต (en080–en089) ---------- */

{ id:"en080", t:"2.4 Present Continuous และ Present Simple เพื่ออนาคต", d:"easy",
  q:"Which sentence uses the Present Continuous for a future arrangement?",
  c:["I am studying English right now.","I studied English last year.","I study English every day.","I am meeting my dentist at three tomorrow."],
  a:3,
  w:"Present Continuous เพื่ออนาคตต้องมีคำบอกเวลาในอนาคตกำกับ และเป็นนัดหมายที่จัดการเรียบร้อยแล้ว",
  e:["ผิด — right now บอกว่าเป็นปัจจุบันขณะนี้ ไม่ใช่อนาคต",
     "ผิด — เป็นอดีต",
     "ผิด — every day บอกความเป็นกิจวัตร ไม่ใช่อนาคต",
     "ถูก — at three tomorrow บอกอนาคตชัดเจน และการนัดหมอฟันเป็นนัดที่ล็อกแล้ว"] },

{ id:"en081", t:"2.4 Present Continuous และ Present Simple เพื่ออนาคต", d:"easy",
  q:"Which sentence uses the Present Simple for a future timetable?",
  c:["The film starts at eight tonight.","The film is starting right now.","The film started at eight.","The film will start, I think."],
  a:0,
  w:"Present Simple เพื่ออนาคตใช้กับตารางเวลาที่ตายตัว เช่น รอบหนัง ตารางรถไฟ ตารางเรียน และกำหนดการทางการ",
  e:["ถูก — รอบฉายหนังเป็นตารางเวลาที่กำหนดไว้ตายตัว จึงใช้ starts",
     "ผิด — right now บอกปัจจุบันขณะนี้",
     "ผิด — เป็นอดีต",
     "ผิด — เป็นการคาดเดาด้วย will ไม่ใช่การอ้างตารางเวลา"] },

{ id:"en082", t:"2.4 Present Continuous และ Present Simple เพื่ออนาคต", d:"easy",
  q:"Which situation uses the Present Simple for the future?",
  c:["นัดกินข้าวกับเพื่อนพรุ่งนี้","ตารางเที่ยวบินที่สายการบินประกาศ","การตัดสินใจทันทีตอนพูด","การคาดเดาว่าพรุ่งนี้อากาศจะดี"],
  a:1,
  w:"Present Simple เพื่ออนาคตสงวนไว้สำหรับตารางเวลาสาธารณะที่คนอื่นกำหนดและเปลี่ยนเองไม่ได้",
  e:["ผิด — นัดส่วนตัวใช้ Present Continuous",
     "ถูก — ตารางบินเป็นกำหนดการทางการที่ตายตัว จึงใช้ Present Simple",
     "ผิด — การตัดสินใจทันทีใช้ will",
     "ผิด — การคาดเดาใช้ will หรือ be going to"] },

{ id:"en083", t:"2.4 Present Continuous และ Present Simple เพื่ออนาคต", d:"medium",
  q:"\"We ____ to Phuket next Friday. We have already booked the hotel.\"",
  c:["fly","flew","are flying","were flying"],
  a:2,
  w:"การจองโรงแรมแล้วแสดงว่าเป็นนัดหมายส่วนตัวที่จัดการเรียบร้อย จึงใช้ Present Continuous เพื่ออนาคต",
  e:["ผิด — Present Simple ใช้กับตารางบินทางการ ไม่ใช่แผนเดินทางของเราเอง",
     "ผิด — เป็นอดีต",
     "ถูก — are flying + next Friday สื่อว่าเป็นนัดที่ล็อกไว้แล้ว",
     "ผิด — เป็นอดีตแบบต่อเนื่อง"] },

{ id:"en084", t:"2.4 Present Continuous และ Present Simple เพื่ออนาคต", d:"hard",
  q:"Which sentence is NOT natural?",
  c:["I am having lunch with my boss tomorrow.","The train arrives at 9:15 tomorrow.","School starts on May 16th.","I am knowing the answer tomorrow."],
  a:3,
  w:"know เป็นกริยาบอกสภาวะ จึงใช้ในรูป continuous ไม่ได้ ไม่ว่าจะสื่อปัจจุบันหรืออนาคตก็ตาม",
  e:["ผิด — ข้อนี้เป็นธรรมชาติ เป็นนัดหมายที่ล็อกแล้ว",
     "ผิด — ข้อนี้เป็นธรรมชาติ เป็นตารางเดินรถ",
     "ผิด — ข้อนี้เป็นธรรมชาติ เป็นกำหนดการเปิดเทอม",
     "ถูก — เป็นข้อที่ไม่ถูก ต้องพูดว่า I will know the answer tomorrow."] },

{ id:"en085", t:"2.4 Present Continuous และ Present Simple เพื่ออนาคต", d:"easy",
  q:"What must a Present Continuous sentence about the future usually include?",
  c:["คำบอกเวลาอนาคตที่ชัดเจน","คำว่า will","กริยาช่อง 2","คำว่า ago"],
  a:0,
  w:"ถ้าไม่มีคำบอกเวลาอนาคตกำกับ ผู้ฟังจะเข้าใจว่ากำลังพูดถึงสิ่งที่เกิดขึ้นอยู่ตอนนี้แทน",
  e:["ถูก — เช่น tomorrow, tonight, next week, at three on Friday",
     "ผิด — ถ้ามี will ก็จะกลายเป็น Future Simple ไม่ใช่รูปนี้",
     "ผิด — กริยาช่อง 2 ใช้กับอดีต",
     "ผิด — ago บอกอดีต"] },

{ id:"en086", t:"2.4 Present Continuous และ Present Simple เพื่ออนาคต", d:"hard",
  q:"Compare: (ก) The bus leaves at seven.  (ข) I am leaving at seven.  Which statement is true?",
  c:["ทั้งสองประโยคผิดไวยากรณ์","(ก) อ้างตารางเวลาที่กำหนดไว้ · (ข) เป็นแผนส่วนตัวที่ผู้พูดจัดการเอง","(ก) เป็นแผนส่วนตัว · (ข) อ้างตารางเวลา","ทั้งสองประโยคมีความหมายเหมือนกัน"],
  a:1,
  w:"Present Simple ใช้กับกำหนดการที่องค์กรกำหนดและผู้พูดเปลี่ยนไม่ได้ ส่วน Present Continuous ใช้กับนัดหมายที่ผู้พูดจัดการเอง",
  e:["ผิด — ทั้งสองประโยคถูกไวยากรณ์",
     "ถูก — เส้นแบ่งอยู่ที่ว่าใครเป็นคนกำหนดเวลานั้น",
     "ผิด — สลับกัน",
     "ผิด — ความหมายต่างกันที่ผู้กำหนดตารางเวลา"] },

{ id:"en087", t:"2.4 Present Continuous และ Present Simple เพื่ออนาคต", d:"easy",
  q:"Complete: \"The exam ____ at nine o'clock on Monday.\"",
  c:["started","is starting right now","starts","was starting"],
  a:2,
  w:"ตารางสอบเป็นกำหนดการทางการที่โรงเรียนกำหนด จึงใช้ Present Simple เพื่ออนาคต",
  e:["ผิด — เป็นอดีต",
     "ผิด — right now ขัดกับ on Monday ที่ยังมาไม่ถึง",
     "ถูก — starts + on Monday เป็นรูปมาตรฐานของตารางเวลา",
     "ผิด — เป็นอดีตแบบต่อเนื่อง"] },

{ id:"en088", t:"2.4 Present Continuous และ Present Simple เพื่ออนาคต", d:"medium",
  q:"Which sentence would a native speaker most likely say about a fixed dinner appointment tonight?",
  c:["I will have dinner with Anna tonight.","I had dinner with Anna tonight.","I have dinner with Anna tonight.","I am having dinner with Anna tonight."],
  a:3,
  w:"นัดหมายส่วนตัวที่ตกลงกับอีกฝ่ายเรียบร้อยแล้ว เจ้าของภาษาใช้ Present Continuous เป็นหลัก",
  e:["ผิด — will ฟังเหมือนเพิ่งตัดสินใจ ไม่สะท้อนว่าเป็นนัดที่ตกลงไว้แล้ว",
     "ผิด — เป็นอดีต แต่มื้อเย็นยังไม่เกิดขึ้น",
     "ผิด — Present Simple สงวนไว้กับตารางเวลาสาธารณะ",
     "ถูก — เป็นรูปที่ธรรมชาติที่สุดสำหรับนัดหมายส่วนตัว"] },

{ id:"en089", t:"2.4 Present Continuous และ Present Simple เพื่ออนาคต", d:"hard",
  q:"\"My flight ____ at 6 a.m., so I ____ my friend at 4 a.m. to go to the airport together.\"",
  c:["leaves / am meeting","is leaving / meet","left / met","will leave / will meet"],
  a:0,
  w:"เวลาบินเป็นตารางของสายการบินจึงใช้ Present Simple ส่วนการนัดเจอเพื่อนเป็นนัดหมายส่วนตัวที่ตกลงกันแล้ว จึงใช้ Present Continuous",
  e:["ถูก — leaves สำหรับตารางบิน และ am meeting สำหรับนัดส่วนตัว",
     "ผิด — สลับกันทั้งสองช่อง",
     "ผิด — เป็นอดีตทั้งคู่ ขัดกับเนื้อความที่ยังไม่เกิด",
     "ผิด — ใช้ได้ในเชิงไวยากรณ์แต่ไม่เป็นธรรมชาติ เพราะทั้งสองอย่างถูกกำหนดไว้แล้ว ไม่ใช่การคาดเดา"] },


/* ---------- 2.5 Future Continuous / Perfect / Perfect Continuous (en090–en100) ---------- */

{ id:"en090", t:"2.5 Future Continuous / Perfect / Perfect Continuous", d:"easy",
  q:"What is the structure of the Future Continuous?",
  c:["will + verb-ing","will be + verb-ing","will have + verb 3","will have been + verb-ing"],
  a:1,
  w:"Future Continuous ใช้ will be + verb-ing เพื่อบอกสิ่งที่จะกำลังดำเนินอยู่ ณ จุดเวลาหนึ่งในอนาคต",
  e:["ผิด — ขาด be ซึ่งจำเป็นเสมอ",
     "ถูก — เช่น At 8 p.m. tomorrow I will be studying.",
     "ผิด — will have + verb 3 เป็น Future Perfect",
     "ผิด — will have been + verb-ing เป็น Future Perfect Continuous"] },

{ id:"en091", t:"2.5 Future Continuous / Perfect / Perfect Continuous", d:"easy",
  q:"What is the structure of the Future Perfect?",
  c:["will be + verb-ing","will + verb 1","will have + verb 3","will have been + verb-ing"],
  a:2,
  w:"Future Perfect ใช้ will have + กริยาช่อง 3 เพื่อบอกว่าเสร็จสิ้นก่อนจุดเวลาหนึ่งในอนาคต",
  e:["ผิด — will be + verb-ing เป็น Future Continuous",
     "ผิด — will + verb 1 เป็น Future Simple",
     "ถูก — เช่น By next June I will have finished school.",
     "ผิด — will have been + verb-ing เป็น Future Perfect Continuous"] },

{ id:"en092", t:"2.5 Future Continuous / Perfect / Perfect Continuous", d:"medium",
  q:"\"This time next week, I ____ on a beach in Krabi.\"",
  c:["will lie","lie","will have lain","will be lying"],
  a:3,
  w:"This time next week เป็นจุดเวลาหนึ่งในอนาคต และประโยคต้องการภาพว่ากำลังทำอยู่ ณ จุดนั้น จึงใช้ Future Continuous",
  e:["ผิด — will lie บอกเพียงว่าจะเกิดขึ้น ไม่ได้เน้นภาพขณะกำลังทำ",
     "ผิด — Present Simple ไม่สื่ออนาคตในบริบทนี้",
     "ผิด — Future Perfect สื่อว่าเสร็จสิ้นไปแล้ว ซึ่งไม่ตรงกับความหมาย",
     "ถูก — will be lying วาดภาพว่ากำลังนอนอยู่พอดี ณ เวลานั้น"] },

{ id:"en093", t:"2.5 Future Continuous / Perfect / Perfect Continuous", d:"medium",
  q:"\"By the time you arrive, I ____ the report.\"",
  c:["will have finished","will be finishing","will finish","finish"],
  a:0,
  w:"By the time เป็นสัญญาณของ Future Perfect เพราะบอกว่างานจะเสร็จก่อนถึงจุดเวลานั้น",
  e:["ถูก — will have finished ระบุชัดว่าเสร็จก่อนจุดเวลาในอนาคต",
     "ผิด — will be finishing สื่อว่ากำลังทำอยู่ ซึ่งขัดกับความหมายว่าเสร็จแล้ว",
     "ผิด — will finish ไม่ได้บอกชัดว่าเสร็จก่อนหรือหลังที่อีกฝ่ายมาถึง",
     "ผิด — Present Simple ไม่สื่ออนาคตในลักษณะนี้"] },

{ id:"en094", t:"2.5 Future Continuous / Perfect / Perfect Continuous", d:"hard",
  q:"\"In September, she ____ here for ten years.\"  Choose the best answer.",
  c:["will work","will have been working","will be working","works"],
  a:1,
  w:"Future Perfect Continuous ใช้บอกระยะเวลาที่สะสมมาจนถึงจุดหนึ่งในอนาคต มักมาคู่กับ for + ช่วงเวลา",
  e:["ผิด — will work ไม่ได้สื่อระยะเวลาที่สะสมมา",
     "ถูก — will have been working for ten years บอกระยะเวลาต่อเนื่องจนถึงเดือนกันยายน",
     "ผิด — will be working บอกว่ากำลังทำ ณ ขณะนั้น แต่ไม่ได้บอกว่าสะสมมานานเท่าไร",
     "ผิด — Present Simple ไม่สื่ออนาคตในบริบทนี้"] },

{ id:"en095", t:"2.5 Future Continuous / Perfect / Perfect Continuous", d:"medium",
  q:"Which time expression most often goes with the Future Perfect?",
  c:["right now","two years ago","by 2030","every Monday"],
  a:2,
  w:"by + จุดเวลา เป็นสัญญาณหลักของ Future Perfect เช่น by 2030, by next month, by the time you come",
  e:["ผิด — right now ใช้กับปัจจุบันขณะนี้",
     "ผิด — ago บอกอดีต",
     "ถูก — by 2030 บอกเส้นตายที่งานต้องเสร็จก่อน",
     "ผิด — every Monday บอกความเป็นกิจวัตร"] },

{ id:"en096", t:"2.5 Future Continuous / Perfect / Perfect Continuous", d:"hard",
  q:"What is the difference between \"I will be working at 9\" and \"I will have worked by 9\"?",
  c:["ความหมายเหมือนกัน","ทั้งสองประโยคผิดไวยากรณ์","ประโยคแรกบอกว่าเสร็จก่อนเก้าโมง · ประโยคหลังบอกว่ากำลังทำ","ประโยคแรกบอกว่ากำลังทำอยู่ตอนเก้าโมง · ประโยคหลังบอกว่าทำเสร็จก่อนเก้าโมง"],
  a:3,
  w:"Future Continuous ตรึงภาพ ณ จุดเวลา ส่วน Future Perfect ตรึงเส้นตายว่าเสร็จก่อนจุดเวลานั้น",
  e:["ผิด — สื่อคนละความหมายชัดเจน",
     "ผิด — ทั้งสองประโยคถูกไวยากรณ์",
     "ผิด — สลับความหมายของทั้งสองประโยค",
     "ถูก — ตัวหนึ่งเน้นว่ากำลังดำเนิน อีกตัวเน้นว่าจบแล้ว"] },

{ id:"en097", t:"2.5 Future Continuous / Perfect / Perfect Continuous", d:"medium",
  q:"Choose the correct Future Perfect sentence.",
  c:["They will have arrived by noon.","They will have arrive by noon.","They will has arrived by noon.","They will have arriving by noon."],
  a:0,
  w:"หลัง will have ต้องเป็นกริยาช่อง 3 เสมอ และ have ไม่เปลี่ยนเป็น has หลัง will",
  e:["ถูก — will have arrived ถูกต้องครบทุกส่วน",
     "ผิด — ต้องเป็นช่อง 3 คือ arrived",
     "ผิด — หลัง will ต้องใช้ have เสมอ ไม่ว่าประธานจะเป็นอะไร",
     "ผิด — รูป -ing ใช้กับ will have been ไม่ใช่ will have"] },

{ id:"en098", t:"2.5 Future Continuous / Perfect / Perfect Continuous", d:"easy",
  q:"Which sentence uses the Future Continuous?",
  c:["I will call you tomorrow.","I will be driving at that time, so I can't answer.","I will have called you by then.","I called you yesterday."],
  a:1,
  w:"Future Continuous ใช้บอกว่าจะกำลังทำอะไรอยู่ ณ จุดเวลาหนึ่งในอนาคต ซึ่งมักใช้อธิบายว่าทำไมทำอย่างอื่นไม่ได้",
  e:["ผิด — เป็น Future Simple",
     "ถูก — will be driving เป็นรูป Future Continuous ที่บอกสิ่งที่จะดำเนินอยู่ตอนนั้น",
     "ผิด — เป็น Future Perfect",
     "ผิด — เป็น Past Simple"] },

{ id:"en099", t:"2.5 Future Continuous / Perfect / Perfect Continuous", d:"hard",
  q:"\"By the end of this year, I ____ Thai for five years.\"",
  c:["will study","will be studying","will have been studying","studied"],
  a:2,
  w:"เมื่อมีทั้งเส้นตายในอนาคต (by the end of this year) และระยะเวลาสะสม (for five years) ต้องใช้ Future Perfect Continuous",
  e:["ผิด — ไม่สื่อระยะเวลาที่สะสมมาถึงจุดนั้น",
     "ผิด — บอกเพียงว่ากำลังเรียนอยู่ตอนนั้น ไม่ได้บอกว่าเรียนมานานเท่าไร",
     "ถูก — will have been studying for five years ครอบคลุมทั้งเส้นตายและระยะเวลา",
     "ผิด — เป็นอดีต ขัดกับ by the end of this year"] },

{ id:"en100", t:"2.5 Future Continuous / Perfect / Perfect Continuous", d:"medium",
  q:"Which sentence politely asks about someone's plan using the Future Continuous?",
  c:["Do you come to the meeting?","Will you come to the meeting right now?","Did you come to the meeting?","Will you be coming to the meeting?"],
  a:3,
  w:"Future Continuous ใช้ถามถึงแผนของอีกฝ่ายอย่างสุภาพ เพราะฟังเหมือนถามข้อเท็จจริง ไม่ใช่การกดดันให้ตอบรับ",
  e:["ผิด — เป็นปัจจุบัน และฟังเหมือนถามกิจวัตร",
     "ผิด — ฟังเหมือนการขอร้องหรือเรียกร้องให้มาทันที",
     "ผิด — เป็นอดีต",
     "ถูก — Will you be coming …? ฟังนุ่มกว่า Will you come …? ซึ่งอาจฟังเหมือนขอร้อง"] },


/* ---------- 2.6 Time expressions (en101–en110) ---------- */

{ id:"en101", t:"2.6 Time expressions", d:"easy",
  q:"Which time expression belongs to the FUTURE?",
  c:["the day after tomorrow","the day before yesterday","last night","an hour ago"],
  a:0,
  w:"the day after tomorrow แปลว่ามะรืนนี้ จึงเป็นอนาคต ส่วนอีกสามตัวล้วนบอกอดีต",
  e:["ถูก — มะรืนนี้ ยังมาไม่ถึง",
     "ผิด — the day before yesterday แปลว่าเมื่อวานซืน เป็นอดีต",
     "ผิด — last night บอกอดีต",
     "ผิด — an hour ago บอกอดีต"] },

{ id:"en102", t:"2.6 Time expressions", d:"easy",
  q:"Which expression signals the Past Simple?",
  c:["in two days","in 2015","soon","by next year"],
  a:1,
  w:"in + ปีที่ผ่านมาแล้ว บอกอดีตที่จบไปแล้ว จึงคู่กับ Past Simple",
  e:["ผิด — in two days หมายถึงอีกสองวันข้างหน้า เป็นอนาคต",
     "ถูก — in 2015 เป็นปีที่ผ่านไปแล้ว จึงใช้กับ Past Simple",
     "ผิด — soon บอกอนาคตอันใกล้",
     "ผิด — by next year เป็นเส้นตายในอนาคต คู่กับ Future Perfect"] },

{ id:"en103", t:"2.6 Time expressions", d:"easy",
  q:"\"in two hours\" means:",
  c:["สองชั่วโมงที่แล้ว","ตลอดสองชั่วโมง","อีกสองชั่วโมงข้างหน้า","ทุกสองชั่วโมง"],
  a:2,
  w:"in + ช่วงเวลา ในบริบทอนาคตแปลว่านับจากนี้ไปอีกเท่านั้น ต่างจาก for + ช่วงเวลา ที่แปลว่าเป็นเวลานานเท่านั้น",
  e:["ผิด — สองชั่วโมงที่แล้วคือ two hours ago",
     "ผิด — ตลอดสองชั่วโมงคือ for two hours",
     "ถูก — I'll be there in two hours. แปลว่าอีกสองชั่วโมงจะถึง",
     "ผิด — ทุกสองชั่วโมงคือ every two hours"] },

{ id:"en104", t:"2.6 Time expressions", d:"hard",
  q:"Which expression usually goes with the Future Perfect?",
  c:["every summer","at the moment","two weeks ago","by the end of the month"],
  a:3,
  w:"by + จุดเวลาในอนาคต บอกเส้นตายที่งานต้องเสร็จก่อน จึงเป็นสัญญาณของ Future Perfect",
  e:["ผิด — every summer บอกความเป็นกิจวัตร คู่กับ Present Simple",
     "ผิด — at the moment คู่กับ Present Continuous",
     "ผิด — ago คู่กับ Past Simple",
     "ถูก — by the end of the month เป็นเส้นตายที่ชัดเจน"] },

{ id:"en105", t:"2.6 Time expressions", d:"hard",
  q:"What is the difference between \"for two years\" and \"in two years\"?",
  c:["for บอกระยะเวลาที่กินไป · in บอกว่าอีกนานเท่าไรจึงจะถึงเวลานั้น","ความหมายเหมือนกัน","for บอกอนาคต · in บอกอดีต","ทั้งสองใช้กับอดีตเท่านั้น"],
  a:0,
  w:"for + ช่วงเวลา บอกว่ากินเวลานานเท่าไร ส่วน in + ช่วงเวลา ในบริบทอนาคตบอกว่าอีกนานเท่าไรจึงจะเกิดขึ้น",
  e:["ถูก — I studied for two years. เทียบกับ I will graduate in two years.",
     "ผิด — ความหมายต่างกันชัดเจน และเป็นจุดที่ผิดกันบ่อย",
     "ผิด — ทั้งสองคำใช้ได้กับหลายกาล ขึ้นอยู่กับบริบท",
     "ผิด — ทั้งสองคำใช้กับอนาคตได้"] },

{ id:"en106", t:"2.6 Time expressions", d:"easy",
  q:"Which expression goes with the Past Continuous most naturally?",
  c:["by next Friday","at eight o'clock last night","every morning","in three days"],
  a:1,
  w:"จุดเวลาหนึ่งในอดีตเป็นบริบทที่เหมาะที่สุดกับ Past Continuous เพราะใช้บอกว่ากำลังทำอะไรอยู่ ณ เวลานั้น",
  e:["ผิด — by next Friday เป็นเส้นตายในอนาคต",
     "ถูก — เช่น At eight o'clock last night I was watching TV.",
     "ผิด — every morning บอกกิจวัตร คู่กับ Present Simple",
     "ผิด — in three days เป็นอนาคต"] },

{ id:"en107", t:"2.6 Time expressions", d:"medium",
  q:"\"the following day\" is used instead of \"tomorrow\" when:",
  c:["พูดถึงอนาคตจากมุมของปัจจุบัน","พูดถึงกิจวัตรประจำวัน","เล่าเรื่องในอดีตแล้วอ้างถึงวันถัดจากวันนั้น","พูดถึงเหตุการณ์ที่ยังไม่แน่นอน"],
  a:2,
  w:"เมื่อเล่าเรื่องในอดีต จุดอ้างอิงเวลาย้ายไปอยู่ในอดีตด้วย tomorrow จึงเปลี่ยนเป็น the following day หรือ the next day",
  e:["ผิด — ถ้าอ้างจากปัจจุบันก็ใช้ tomorrow ได้ตามปกติ",
     "ผิด — กิจวัตรใช้คำอย่าง every day",
     "ถูก — เช่น He arrived on Monday and left the following day.",
     "ผิด — ความไม่แน่นอนแสดงด้วย probably หรือ maybe ไม่ใช่คำบอกวัน"] },

{ id:"en108", t:"2.6 Time expressions", d:"hard",
  q:"Which sentence has a MISMATCH between the tense and the time expression?",
  c:["I will see him tomorrow.","I saw him yesterday.","I am seeing him tomorrow.","I will see him yesterday."],
  a:3,
  w:"yesterday บอกอดีต จึงใช้กับ will ซึ่งเป็นอนาคตไม่ได้ คู่ของกาลกับคำบอกเวลาต้องสอดคล้องกันเสมอ",
  e:["ผิด — will + tomorrow เข้าคู่กันถูกต้อง",
     "ผิด — saw + yesterday เข้าคู่กันถูกต้อง",
     "ผิด — Present Continuous + tomorrow ใช้กับนัดหมายได้ถูกต้อง",
     "ถูก — เป็นข้อที่ขัดกัน เพราะ will เป็นอนาคตแต่ yesterday เป็นอดีต"] },

{ id:"en109", t:"2.6 Time expressions", d:"medium",
  q:"Which of these signals the Present Perfect rather than the Past Simple?",
  c:["since 2020","last week","in 2020","three days ago"],
  a:0,
  w:"since + จุดเริ่มต้น บอกช่วงเวลาที่ต่อเนื่องมาถึงปัจจุบัน จึงคู่กับ Present Perfect ส่วนอีกสามตัวเป็นอดีตที่ปิดแล้ว",
  e:["ถูก — since 2020 หมายถึงตั้งแต่ปี 2020 จนถึงตอนนี้",
     "ผิด — last week เป็นอดีตที่จบแล้ว คู่กับ Past Simple",
     "ผิด — in 2020 ระบุปีที่จบไปแล้ว คู่กับ Past Simple",
     "ผิด — ago คู่กับ Past Simple เสมอ"] },

{ id:"en110", t:"2.6 Time expressions", d:"easy",
  q:"Which pair is correctly matched?",
  c:["tonight – Past Simple","next month – Future","last year – Future","two hours ago – Future"],
  a:1,
  w:"next + ช่วงเวลา บอกอนาคต จึงจับคู่กับรูปอนาคต ส่วน last และ ago จับคู่กับอดีต",
  e:["ผิด — tonight มักหมายถึงคืนนี้ที่ยังมาไม่ถึง จึงใช้กับรูปอนาคต",
     "ถูก — next month คู่กับรูปอนาคตได้ทุกแบบ",
     "ผิด — last year เป็นอดีต",
     "ผิด — ago เป็นอดีตเสมอ"] },


/* ---------- 3.1 ตารางเทียบทุกรูปในที่เดียว (en111–en119) ---------- */

{ id:"en111", t:"3.1 ตารางเทียบทุกรูปในที่เดียว", d:"easy",
  q:"Match the form to its structure: Past Continuous",
  c:["did + verb 1","will be + verb-ing","was/were + verb-ing","have/has + verb 3"],
  a:2,
  w:"Past Continuous = was/were + verb-ing ส่วน will be + verb-ing คือ Future Continuous ซึ่งใช้ be ตัวเดียวกันแต่ต่างที่กริยาช่วยด้านหน้า",
  e:["ผิด — เป็นโครงสร้างคำถามและปฏิเสธของ Past Simple",
     "ผิด — เป็น Future Continuous",
     "ถูก — was สำหรับเอกพจน์ were สำหรับพหูพจน์",
     "ผิด — เป็น Present Perfect"] },

{ id:"en112", t:"3.1 ตารางเทียบทุกรูปในที่เดียว", d:"medium",
  q:"Which form is used for an action completed BEFORE a point in the future?",
  c:["Future Simple","Future Continuous","Present Continuous","Future Perfect"],
  a:3,
  w:"Future Perfect (will have + verb 3) บอกว่างานเสร็จก่อนถึงจุดเวลาที่ระบุในอนาคต",
  e:["ผิด — Future Simple บอกเพียงว่าจะเกิดขึ้น ไม่ได้บอกว่าเสร็จก่อนอะไร",
     "ผิด — Future Continuous บอกว่ากำลังดำเนินอยู่ ณ จุดนั้น",
     "ผิด — Present Continuous ใช้กับนัดหมาย",
     "ถูก — เช่น I will have finished by six."] },

{ id:"en113", t:"3.1 ตารางเทียบทุกรูปในที่เดียว", d:"hard",
  q:"Which two forms both use \"verb-ing\" after a form of \"be\"?",
  c:["Past Continuous และ Future Continuous","Past Simple และ Future Simple","Present Perfect และ Future Perfect","Past Simple และ Present Simple"],
  a:0,
  w:"ทั้งสองรูปใช้ verb to be ตามด้วย -ing ต่างกันที่ Past Continuous ใช้ was/were ส่วน Future Continuous ใช้ will be",
  e:["ถูก — was/were + -ing กับ will be + -ing ใช้หลักเดียวกัน",
     "ผิด — ทั้งสองรูปนี้ตามด้วยกริยารูปเปล่าหรือช่อง 2 ไม่ใช่ -ing",
     "ผิด — ทั้งสองรูปนี้ตามด้วยกริยาช่อง 3",
     "ผิด — ไม่มีรูปใดใช้ -ing"] },

{ id:"en114", t:"3.1 ตารางเทียบทุกรูปในที่เดียว", d:"hard",
  q:"Put these in order from \"earliest completion\" to \"still ongoing\" at a future point:  ① will have finished  ② will be finishing  ③ will finish",
  c:["① → ③ → ②","② → ① → ③","③ → ① → ②","① → ② → ③"],
  a:0,
  w:"will have finished บอกว่าเสร็จก่อนจุดเวลานั้น · will finish บอกว่าจะเกิดขึ้นโดยไม่ระบุความสัมพันธ์ · will be finishing บอกว่ายังกำลังทำอยู่ ณ จุดนั้น",
  e:["ถูก — เรียงจากเสร็จแล้ว ไปยังกลาง ๆ ไปจนถึงยังทำอยู่",
     "ผิด — will be finishing เป็นตัวที่ยังไม่เสร็จ จึงอยู่ท้ายสุด ไม่ใช่ต้น",
     "ผิด — will finish ไม่ได้ยืนยันว่าเสร็จก่อน จึงไม่ควรอยู่หน้า will have finished",
     "ผิด — สลับสองตัวท้าย"] },

{ id:"en115", t:"3.1 ตารางเทียบทุกรูปในที่เดียว", d:"easy",
  q:"Which form uses \"will have been + verb-ing\"?",
  c:["Future Simple","Future Perfect Continuous","Future Perfect","Future Continuous"],
  a:1,
  w:"Future Perfect Continuous ใช้ will have been + verb-ing เพื่อบอกระยะเวลาที่สะสมมาถึงจุดหนึ่งในอนาคต",
  e:["ผิด — Future Simple คือ will + verb 1",
     "ถูก — เช่น By May she will have been teaching for ten years.",
     "ผิด — Future Perfect คือ will have + verb 3",
     "ผิด — Future Continuous คือ will be + verb-ing"] },

{ id:"en116", t:"3.1 ตารางเทียบทุกรูปในที่เดียว", d:"medium",
  q:"Which past form corresponds structurally to the Future Continuous?",
  c:["Past Simple","Present Perfect","Past Continuous","Past Perfect"],
  a:2,
  w:"ทั้งคู่ใช้ be + verb-ing เพื่อบอกภาพขณะกำลังทำ ต่างกันเพียงว่าจุดอ้างอิงอยู่ในอดีตหรืออนาคต",
  e:["ผิด — Past Simple ใช้กริยาช่อง 2 เดี่ยว ๆ",
     "ผิด — Present Perfect ใช้ have + verb 3",
     "ถูก — was/were + -ing เทียบกับ will be + -ing เป็นคู่ขนานกัน",
     "ผิด — Past Perfect ใช้ had + verb 3"] },

{ id:"en117", t:"3.1 ตารางเทียบทุกรูปในที่เดียว", d:"olympiad",
  q:"Which sentence pair correctly contrasts \"a point in time\" with \"a deadline\"?",
  c:["At 9 I will finish. / By 9 I will be finishing.","At 9 I finished. / By 9 I finish.","At 9 I will have finished. / By 9 I will be working.","At 9 I will be working. / By 9 I will have finished."],
  a:3,
  w:"at + จุดเวลา ใช้กับ Future Continuous เพื่อบอกว่ากำลังทำอยู่ตอนนั้น ส่วน by + จุดเวลา ใช้กับ Future Perfect เพื่อบอกเส้นตาย",
  e:["ผิด — สลับกัน by ควรคู่กับ Future Perfect ไม่ใช่ Future Continuous",
     "ผิด — เป็นรูปอดีตและปัจจุบัน ไม่ตรงกับโจทย์ที่ถามถึงอนาคต",
     "ผิด — สลับกันทั้งคู่",
     "ถูก — at คู่กับภาพขณะทำ และ by คู่กับเส้นตายที่ต้องเสร็จก่อน"] },

{ id:"en118", t:"3.1 ตารางเทียบทุกรูปในที่เดียว", d:"medium",
  q:"Which is the single most reliable way to choose a tense in an exam?",
  c:["ดูคำบอกเวลาและเจตนาของผู้พูดเป็นหลัก","ดูว่าประโยคยาวหรือสั้น","เลือกรูปที่ซับซ้อนที่สุดไว้ก่อน","เลือกรูปเดียวกับข้อก่อนหน้า"],
  a:0,
  w:"คำบอกเวลาบอกว่ากรอบเวลาอยู่ตรงไหน ส่วนเจตนาบอกว่าผู้พูดต้องการสื่ออะไร สองอย่างนี้ตัดตัวเลือกผิดออกได้เกือบหมด",
  e:["ถูก — เป็นวิธีที่ใช้ได้กับทุกข้อโดยไม่ต้องท่องตารางทั้งหมด",
     "ผิด — ความยาวของประโยคไม่เกี่ยวกับการเลือกกาล",
     "ผิด — รูปที่ซับซ้อนกว่าไม่ได้แปลว่าถูกกว่า",
     "ผิด — แต่ละข้อเป็นอิสระต่อกัน"] },

{ id:"en119", t:"3.1 ตารางเทียบทุกรูปในที่เดียว", d:"easy",
  q:"Which form is \"will + verb 1\"?",
  c:["Future Continuous","Future Simple","Future Perfect","Past Simple"],
  a:1,
  w:"Future Simple คือ will ตามด้วยกริยาช่อง 1 เป็นรูปอนาคตที่พื้นฐานที่สุด",
  e:["ผิด — Future Continuous ต้องมี be + -ing",
     "ถูก — เช่น I will go · She will call",
     "ผิด — Future Perfect ต้องมี have + verb 3",
     "ผิด — Past Simple ใช้กริยาช่อง 2 ไม่มี will"] },


/* ---------- 3.2 กับดักที่เสียคะแนนบ่อยที่สุด (en120–en130) ---------- */

{ id:"en120", t:"3.2 กับดักที่เสียคะแนนบ่อยที่สุด", d:"easy",
  q:"Find the mistake: \"He didn't came to school yesterday.\"",
  c:["didn't ต้องเป็น doesn't","yesterday ต้องเป็น today","came ต้องเป็น come","ไม่มีที่ผิด"],
  a:2,
  w:"เมื่อมี did หรือ didn't อยู่แล้ว กริยาหลักต้องกลับเป็นช่อง 1 เพราะ did แบกความเป็นอดีตไว้แทนแล้ว",
  e:["ผิด — doesn't เป็นปัจจุบัน ยิ่งขัดกับ yesterday",
     "ผิด — คำบอกเวลาไม่ใช่จุดที่ผิด",
     "ถูก — ต้องเป็น He didn't come to school yesterday.",
     "ผิด — ประโยคนี้มีที่ผิดชัดเจน"] },

{ id:"en121", t:"3.2 กับดักที่เสียคะแนนบ่อยที่สุด", d:"hard",
  q:"Find the mistake: \"I will tell you when I will finish.\"",
  c:["will tell ต้องเป็น tell","ไม่มีที่ผิด","when ต้องเป็น while","will finish ต้องเป็น finish"],
  a:3,
  w:"ในอนุประโยคที่ขึ้นต้นด้วย when, if, before, after, as soon as ให้ใช้ Present Simple แม้ความหมายจะเป็นอนาคต",
  e:["ผิด — ประโยคหลักใช้ will ได้ตามปกติ",
     "ผิด — มีที่ผิดอยู่ในอนุประโยค",
     "ผิด — when ถูกต้องแล้วในบริบทนี้",
     "ถูก — ต้องเป็น I will tell you when I finish."] },

{ id:"en122", t:"3.2 กับดักที่เสียคะแนนบ่อยที่สุด", d:"hard",
  q:"Find the mistake: \"I have seen that movie last night.\"",
  c:["have seen ต้องเป็น saw","last night ต้องตัดออกเท่านั้น","seen ต้องเป็น see","ไม่มีที่ผิด"],
  a:0,
  w:"Present Perfect ใช้กับคำบอกเวลาอดีตที่ระบุชัดเจนไม่ได้ เมื่อมี last night ต้องเปลี่ยนเป็น Past Simple",
  e:["ถูก — ต้องเป็น I saw that movie last night.",
     "ผิด — ตัดคำบอกเวลาออกก็แก้ได้ แต่วิธีที่ตรงกับความหมายเดิมคือเปลี่ยนกาล",
     "ผิด — หลัง have ต้องเป็นช่อง 3 อยู่แล้ว",
     "ผิด — ประโยคนี้มีที่ผิด"] },

{ id:"en123", t:"3.2 กับดักที่เสียคะแนนบ่อยที่สุด", d:"hard",
  q:"Find the mistake: \"While I was walk to school, I met my friend.\"",
  c:["met ต้องเป็น was meeting","was walk ต้องเป็น was walking","While ต้องเป็น When","ไม่มีที่ผิด"],
  a:1,
  w:"หลัง was/were ต้องตามด้วยกริยาเติม -ing เสมอ จะใช้กริยารูปเปล่าไม่ได้",
  e:["ผิด — met เป็นเหตุการณ์แวบเดียว ใช้ Past Simple ถูกแล้ว",
     "ถูก — ต้องเป็น While I was walking to school …",
     "ผิด — While ใช้ถูกแล้วเพราะตามด้วยเหตุการณ์ยาว",
     "ผิด — มีที่ผิดที่รูปกริยา"] },

{ id:"en124", t:"3.2 กับดักที่เสียคะแนนบ่อยที่สุด", d:"medium",
  q:"Find the mistake: \"She will goes to the party.\"",
  c:["will ต้องเป็น wills","She ต้องเป็น They","goes ต้องเป็น go","ไม่มีที่ผิด"],
  a:2,
  w:"กริยาที่ตามหลัง will ต้องเป็นช่อง 1 รูปเปล่าเสมอ ไม่เติม s ตามประธาน",
  e:["ผิด — will ไม่เปลี่ยนรูปตามประธาน",
     "ผิด — ประธานไม่ใช่จุดที่ผิด",
     "ถูก — ต้องเป็น She will go to the party.",
     "ผิด — มีที่ผิดที่รูปกริยาหลัง will"] },

{ id:"en125", t:"3.2 กับดักที่เสียคะแนนบ่อยที่สุด", d:"hard",
  q:"Find the mistake: \"They are going to visiting their grandmother.\"",
  c:["are ต้องเป็น is","going to ต้องเป็น go to","ไม่มีที่ผิด","visiting ต้องเป็น visit"],
  a:3,
  w:"โครงสร้าง be going to ต้องตามด้วยกริยาช่อง 1 รูปเปล่า ไม่ใช่รูป -ing",
  e:["ผิด — They เป็นพหูพจน์ จึงใช้ are ถูกแล้ว",
     "ผิด — going to เป็นส่วนหนึ่งของโครงสร้างนี้ เปลี่ยนเป็น go to ไม่ได้",
     "ผิด — มีที่ผิดที่รูปกริยาหลัง going to",
     "ถูก — ต้องเป็น They are going to visit their grandmother."] },

{ id:"en126", t:"3.2 กับดักที่เสียคะแนนบ่อยที่สุด", d:"medium",
  q:"Find the mistake: \"Yesterday I am going to the market.\"",
  c:["am going ต้องเป็น went","Yesterday ต้องอยู่ท้ายประโยคเท่านั้น","the market ต้องเป็น a market","ไม่มีที่ผิด"],
  a:0,
  w:"Yesterday บอกอดีต จึงต้องใช้กริยาในรูปอดีต ในที่นี้คือ went",
  e:["ถูก — ต้องเป็น Yesterday I went to the market.",
     "ผิด — Yesterday วางต้นประโยคได้ปกติ",
     "ผิด — the market ใช้ได้เมื่อหมายถึงตลาดที่ทั้งสองฝ่ายรู้จัก",
     "ผิด — กาลของกริยาไม่สอดคล้องกับคำบอกเวลา"] },

{ id:"en127", t:"3.2 กับดักที่เสียคะแนนบ่อยที่สุด", d:"hard",
  q:"Find the mistake: \"I was knowing the answer, but I forgot it.\"",
  c:["forgot ต้องเป็น was forgetting","was knowing ต้องเป็น knew","but ต้องเป็น and","ไม่มีที่ผิด"],
  a:1,
  w:"know เป็นกริยาบอกสภาวะ จึงใช้ในรูป continuous ไม่ได้ ต้องใช้ Past Simple คือ knew",
  e:["ผิด — forget เป็นเหตุการณ์แวบเดียว ใช้ Past Simple ถูกแล้ว",
     "ถูก — ต้องเป็น I knew the answer, but I forgot it.",
     "ผิด — but เชื่อมความขัดแย้งได้ถูกต้อง",
     "ผิด — มีที่ผิดที่กริยาบอกสภาวะ"] },

{ id:"en128", t:"3.2 กับดักที่เสียคะแนนบ่อยที่สุด", d:"easy",
  q:"Find the mistake: \"Did you went to the concert?\"",
  c:["Did ต้องเป็น Do","you ต้องเป็น your","went ต้องเป็น go","ไม่มีที่ผิด"],
  a:2,
  w:"เมื่อ Did ขึ้นต้นคำถามแล้ว กริยาหลักต้องกลับเป็นช่อง 1 เสมอ",
  e:["ผิด — Do เป็นปัจจุบัน ซึ่งไม่เข้ากับบริบทที่ถามถึงอดีต",
     "ผิด — you เป็นประธาน ใช้ถูกแล้ว",
     "ถูก — ต้องเป็น Did you go to the concert?",
     "ผิด — มีที่ผิดที่รูปกริยาหลัง Did"] },

{ id:"en129", t:"3.2 กับดักที่เสียคะแนนบ่อยที่สุด", d:"medium",
  q:"Find the mistake: \"He will have finish the work by Friday.\"",
  c:["will ต้องตัดออก","have ต้องเป็น has","ไม่มีที่ผิด","finish ต้องเป็น finished"],
  a:3,
  w:"หลัง will have ต้องเป็นกริยาช่อง 3 เสมอ และ have ไม่เปลี่ยนเป็น has หลัง will",
  e:["ผิด — will จำเป็นสำหรับรูป Future Perfect",
     "ผิด — หลัง will ต้องใช้ have เสมอ ไม่ว่าประธานจะเป็นอะไร",
     "ผิด — มีที่ผิดที่รูปกริยาหลัง will have",
     "ถูก — ต้องเป็น He will have finished the work by Friday."] },

{ id:"en130", t:"3.2 กับดักที่เสียคะแนนบ่อยที่สุด", d:"hard",
  q:"Which sentence is completely correct?",
  c:["If it rains tomorrow, we will stay home.","If it will rain tomorrow, we will stay home.","If it rains tomorrow, we stay home because we will be tired.","If it will rain tomorrow, we stay home."],
  a:0,
  w:"ประโยคเงื่อนไขแบบที่ 1 ใช้ if + Present Simple ในอนุประโยค และ will + verb 1 ในประโยคหลัก",
  e:["ถูก — rains ในอนุประโยค และ will stay ในประโยคหลัก ถูกต้องตามแบบแผน",
     "ผิด — ห้ามใช้ will ในอนุประโยคที่ขึ้นต้นด้วย if",
     "ผิด — ประโยคหลักควรใช้ will stay เพื่อให้เข้ากับแบบแผนของเงื่อนไขแบบที่ 1",
     "ผิด — ผิดทั้งสองส่วน ทั้งใส่ will ใน if และไม่ใส่ will ในประโยคหลัก"] },


/* ---------- 4.1 ฝึกแยก Past Simple กับ Past Continuous (en131–en137) ---------- */

{ id:"en131", t:"4.1 ฝึกแยก Past Simple กับ Past Continuous", d:"medium",
  q:"\"When the guests ____, we ____ the table.\"  (แขกมาถึงตอนที่เรากำลังจัดโต๊ะอยู่)",
  c:["were arriving / set","arrived / were setting","arrived / set","were arriving / were setting"],
  a:1,
  w:"การมาถึงเป็นเหตุการณ์แวบเดียวจึงใช้ Past Simple ส่วนการจัดโต๊ะเป็นสิ่งที่กำลังทำอยู่ จึงใช้ Past Continuous",
  e:["ผิด — สลับกัน ทำให้การจัดโต๊ะกลายเป็นเหตุการณ์แวบเดียว",
     "ถูก — arrived (สั้น) แทรกเข้ามาระหว่าง were setting (ยาว) ตรงกับความหมายในวงเล็บ",
     "ผิด — Past Simple ทั้งคู่ อ่านได้ว่าแขกมาก่อนแล้วเราจึงเริ่มจัดโต๊ะ",
     "ผิด — การมาถึงไม่ใช่เหตุการณ์ที่กินเวลาในบริบทนี้"] },

{ id:"en132", t:"4.1 ฝึกแยก Past Simple กับ Past Continuous", d:"medium",
  q:"\"She ____ her bag on the bus while she ____ home.\"",
  c:["was losing / travelled","lost / travelled","lost / was travelling","was losing / was travelling"],
  a:2,
  w:"การทำของหายเกิดขึ้นในชั่วขณะจึงใช้ Past Simple ส่วนการเดินทางเป็นฉากหลังที่กินเวลา จึงใช้ Past Continuous หลัง while",
  e:["ผิด — สลับกัน ทำให้การทำของหายกลายเป็นเหตุการณ์ยาว",
     "ผิด — while ต้องการฉากหลังในรูป continuous",
     "ถูก — lost (สั้น) เกิดขึ้นระหว่าง was travelling (ยาว)",
     "ผิด — การทำของหายไม่ใช่เหตุการณ์ที่กินเวลา"] },

{ id:"en133", t:"4.1 ฝึกแยก Past Simple กับ Past Continuous", d:"hard",
  q:"\"I ____ my homework, so I ____ the doorbell.\"  (ฉันมัวทำการบ้านอยู่ เลยไม่ได้ยินกริ่ง)",
  c:["did / didn't hear","was doing / wasn't hearing","did / wasn't hearing","was doing / didn't hear"],
  a:3,
  w:"การทำการบ้านเป็นสภาพที่ดำเนินอยู่และเป็นเหตุผลว่าทำไมไม่ได้ยิน จึงใช้ Past Continuous ส่วน hear เป็นกริยาบอกสภาวะ จึงใช้รูป continuous ไม่ได้",
  e:["ผิด — did ไม่ได้สื่อว่ากำลังมัวทำอยู่ ซึ่งเป็นเหตุผลของการไม่ได้ยิน",
     "ผิด — ผิดที่ wasn't hearing เพราะ hear เป็นกริยาบอกสภาวะ",
     "ผิด — hear ใช้รูป continuous ไม่ได้",
     "ถูก — was doing เป็นฉากหลัง และ didn't hear ถูกต้องเพราะ hear เป็นกริยาบอกสภาวะ"] },

{ id:"en134", t:"4.1 ฝึกแยก Past Simple กับ Past Continuous", d:"easy",
  q:"\"Last summer we ____ to Chiang Rai and ____ three temples.\"",
  c:["went / visited","were going / were visiting","went / were visiting","were going / visited"],
  a:0,
  w:"เป็นการเล่าเหตุการณ์ที่จบไปแล้วเรียงต่อกัน จึงใช้ Past Simple ทั้งสองตัว",
  e:["ถูก — went และ visited เล่าลำดับเหตุการณ์ที่จบแล้วได้ตรงที่สุด",
     "ผิด — รูป continuous ทั้งคู่ทำให้ดูเหมือนสองเหตุการณ์กำลังดำเนินพร้อมกัน",
     "ผิด — กาลปนกันโดยไม่มีเหตุผลทางความหมาย",
     "ผิด — กาลปนกันเช่นกัน"] },

{ id:"en135", t:"4.1 ฝึกแยก Past Simple กับ Past Continuous", d:"medium",
  q:"\"The baby ____ when I ____ into the room, so I closed the door quietly.\"",
  c:["slept / walked","was sleeping / walked","slept / was walking","was sleeping / was walking"],
  a:1,
  w:"เด็กหลับอยู่แล้วเป็นสภาพที่ดำเนินอยู่ ส่วนการเดินเข้าห้องเป็นจุดเวลาที่อ้างอิง จึงใช้ Past Continuous คู่กับ Past Simple",
  e:["ผิด — slept ไม่ได้สื่อว่ากำลังหลับอยู่ ณ จังหวะที่เดินเข้าไป",
     "ถูก — was sleeping เป็นสภาพที่เป็นอยู่ และ walked คือจังหวะที่เข้าไปพบ",
     "ผิด — สลับกัน ทำให้การเดินเข้าห้องกลายเป็นฉากหลัง",
     "ผิด — ใช้ continuous ทั้งคู่ ทำให้ไม่มีจุดเวลาอ้างอิงที่ชัดเจน"] },

{ id:"en136", t:"4.1 ฝึกแยก Past Simple กับ Past Continuous", d:"olympiad",
  q:"\"He ____ at the office at three o'clock yesterday, but he ____ the email until this morning.\"",
  c:["worked / wasn't seeing","worked / didn't see","was working / didn't see","was working / wasn't seeing"],
  a:2,
  w:"at three o'clock yesterday เป็นจุดเวลาหนึ่งในอดีต ซึ่งต้องใช้ Past Continuous เพื่อบอกว่ากำลังทำอะไรอยู่ ณ จุดนั้น ส่วน see เป็นกริยาบอกสภาวะในความหมายว่าเห็น จึงต้องใช้ didn't see ไม่ใช่ wasn't seeing",
  e:["ผิด — see ใช้รูป continuous ไม่ได้ในความหมายนี้",
     "ผิด — worked ไม่เข้ากับจุดเวลาเดี่ยวอย่าง at three o'clock ซึ่งต้องการภาพว่ากำลังทำอยู่ตอนนั้น",
     "ถูก — was working บอกว่ากำลังทำงานอยู่ตอนบ่ายสาม และ didn't see ถูกต้องเพราะ see เป็นกริยาบอกสภาวะ",
     "ผิด — wasn't seeing ผิดเพราะ see เป็นกริยาบอกสภาวะ"] },

{ id:"en137", t:"4.1 ฝึกแยก Past Simple กับ Past Continuous", d:"medium",
  q:"Which sentence correctly shows TWO long actions happening at the same time?",
  c:["He cooked while she studied.","He was cooking while she studied.","He cooked while she was studying.","He was cooking while she was studying."],
  a:3,
  w:"เมื่อทั้งสองเหตุการณ์เป็นกิจกรรมยาวที่ดำเนินไปพร้อมกัน ใช้ Past Continuous ทั้งสองฝั่งจึงตรงความหมายที่สุด",
  e:["ผิด — Past Simple ทั้งคู่สื่อว่าเป็นเหตุการณ์ที่จบแล้ว ไม่ได้เน้นการทับซ้อนกัน",
     "ผิด — เป็นรูปแบบเหตุการณ์ยาวกับเหตุการณ์สั้นเช่นกัน",
     "ผิด — เป็นรูปแบบเหตุการณ์สั้นแทรกเหตุการณ์ยาว ไม่ใช่สองเหตุการณ์ยาวคู่กัน",
     "ถูก — was cooking / was studying วาดภาพสองกิจกรรมที่ดำเนินคู่ขนานได้ชัดที่สุด"] },


/* ---------- 4.2 ฝึกเลือกรูปอนาคต (en138–en144) ---------- */

{ id:"en138", t:"4.2 ฝึกเลือกรูปอนาคต", d:"medium",
  q:"\"A: This box is very heavy.  B: ____ you.\"",
  c:["I will help","I am going to help","I help","I helped"],
  a:0,
  w:"B เพิ่งรู้ว่ากล่องหนักตอนที่ A บอก จึงเป็นการเสนอตัวช่วยทันที ซึ่งเป็นหน้าที่ของ will",
  e:["ถูก — การเสนอตัวช่วยเดี๋ยวนั้นใช้ will เสมอ",
     "ผิด — be going to สื่อว่าตั้งใจไว้ก่อน ซึ่งเป็นไปไม่ได้เพราะเพิ่งรู้",
     "ผิด — Present Simple ไม่สื่อเจตนาในอนาคต",
     "ผิด — เป็นอดีต ขัดกับสถานการณ์"] },

{ id:"en139", t:"4.2 ฝึกเลือกรูปอนาคต", d:"hard",
  q:"\"I have already bought the paint. I ____ my room this weekend.\"",
  c:["will paint","am going to paint","paint","painted"],
  a:1,
  w:"การซื้อสีไว้แล้วเป็นหลักฐานว่ามีแผนมาก่อน จึงใช้ be going to",
  e:["ผิด — will ฟังเหมือนเพิ่งตัดสินใจ ซึ่งขัดกับการที่ซื้อของเตรียมไว้แล้ว",
     "ถูก — สีที่ซื้อไว้ยืนยันว่าเป็นความตั้งใจที่มีอยู่ก่อน",
     "ผิด — Present Simple ใช้กับตารางเวลาสาธารณะ",
     "ผิด — เป็นอดีต ขัดกับ this weekend"] },

{ id:"en140", t:"4.2 ฝึกเลือกรูปอนาคต", d:"easy",
  q:"\"The concert ____ at 7 p.m. on Saturday.\"",
  c:["will start","is going to start","starts","started"],
  a:2,
  w:"เวลาเริ่มคอนเสิร์ตเป็นกำหนดการทางการที่ผู้จัดกำหนดไว้ จึงใช้ Present Simple เพื่ออนาคต",
  e:["ผิด — will ใช้กับการคาดการณ์ ไม่ใช่กำหนดการทางการ",
     "ผิด — be going to ใช้กับความตั้งใจส่วนบุคคล",
     "ถูก — ตารางเวลาของงานใช้ Present Simple",
     "ผิด — เป็นอดีต ขัดกับ on Saturday ที่ยังมาไม่ถึง"] },

{ id:"en141", t:"4.2 ฝึกเลือกรูปอนาคต", d:"hard",
  q:"\"Don't call me at eight. I ____ my online class then.\"",
  c:["will attend","attend","will have attended","will be attending"],
  a:3,
  w:"ประโยคต้องการบอกว่า ณ เวลาแปดโมงจะกำลังเรียนอยู่ จึงเป็น Future Continuous ซึ่งเป็นเหตุผลว่าทำไมห้ามโทรมา",
  e:["ผิด — will attend บอกเพียงว่าจะเข้าเรียน ไม่ได้บอกว่ากำลังเรียนอยู่ตอนนั้น",
     "ผิด — Present Simple ไม่สื่ออนาคตในบริบทนี้",
     "ผิด — Future Perfect สื่อว่าเรียนจบไปแล้วก่อนแปดโมง ซึ่งขัดกับเหตุผลที่ห้ามโทร",
     "ถูก — will be attending วาดภาพว่ากำลังเรียนอยู่พอดี ณ เวลาแปดโมง"] },

{ id:"en142", t:"4.2 ฝึกเลือกรูปอนาคต", d:"hard",
  q:"\"I ____ my grandparents on Sunday. We arranged it last week.\"",
  c:["am visiting","will visit","visit","visited"],
  a:0,
  w:"การนัดกันไว้เมื่อสัปดาห์ก่อนแสดงว่าเป็นนัดหมายที่ตกลงเรียบร้อยแล้ว จึงใช้ Present Continuous เพื่ออนาคต",
  e:["ถูก — am visiting + on Sunday เป็นรูปมาตรฐานของนัดหมายส่วนตัว",
     "ผิด — will ไม่สะท้อนว่าเป็นนัดที่ตกลงกันไว้แล้ว",
     "ผิด — Present Simple สงวนไว้กับตารางเวลาสาธารณะ",
     "ผิด — เป็นอดีต แต่การไปเยี่ยมยังไม่เกิดขึ้น"] },

{ id:"en143", t:"4.2 ฝึกเลือกรูปอนาคต", d:"hard",
  q:"\"By the time the movie ends, we ____ here for three hours.\"",
  c:["will sit","will have been sitting","will be sitting","sit"],
  a:1,
  w:"มีทั้งเส้นตายในอนาคต (by the time) และระยะเวลาสะสม (for three hours) จึงต้องใช้ Future Perfect Continuous",
  e:["ผิด — ไม่สื่อระยะเวลาที่สะสมมา",
     "ถูก — will have been sitting for three hours ครบทั้งเส้นตายและระยะเวลา",
     "ผิด — บอกเพียงว่ากำลังนั่งอยู่ ไม่ได้บอกว่านั่งมานานเท่าไร",
     "ผิด — Present Simple ไม่สื่ออนาคตในบริบทนี้"] },

{ id:"en144", t:"4.2 ฝึกเลือกรูปอนาคต", d:"olympiad",
  q:"\"A: Have you decided about the trip?  B: Yes. We ____ to Japan in April — we ____ the flights yesterday and I ____ you the itinerary as soon as I get home.\"",
  c:["will go / booked / am sending","go / will book / send","are going / booked / will send","are going / will book / am sending"],
  a:2,
  w:"การจองตั๋วแล้วทำให้เป็นแผนที่ล็อกแล้ว จึงใช้ Present Continuous เพื่ออนาคต · การจองเกิดเมื่อวานจึงเป็น Past Simple · การจะส่งกำหนดการเป็นการตัดสินใจตอนพูด จึงใช้ will",
  e:["ผิด — will go ไม่สะท้อนว่าจองตั๋วเรียบร้อยแล้ว และ am sending เป็นนัดหมายที่ยังไม่ได้จัดการ",
     "ผิด — ผิดทั้งสามช่อง โดยเฉพาะ will book ที่ขัดกับคำว่า yesterday",
     "ถูก — ถูกครบทั้งสามช่อง ทั้งแผนที่ล็อกแล้ว อดีตที่จบแล้ว และการตัดสินใจทันที",
     "ผิด — will book ขัดกับ yesterday ซึ่งบอกว่าจองไปแล้ว"] },


/* ---------- 4.3 ฝึกจับผิดประโยค (en145–en150) ---------- */

{ id:"en145", t:"4.3 ฝึกจับผิดประโยค", d:"medium",
  q:"Which negative past sentence has NO mistake?",
  c:["She didn't finished her lunch.","She doesn't finished her lunch.","She not finish her lunch.","She didn't finish her lunch."],
  a:3,
  w:"รูปปฏิเสธของ Past Simple คือ didn't + กริยาช่อง 1",
  e:["ผิด — หลัง didn't ต้องเป็นช่อง 1 คือ finish",
     "ผิด — doesn't เป็นปัจจุบัน และหลัง doesn't ต้องเป็นช่อง 1 เช่นกัน",
     "ผิด — กริยาแท้ต้องใช้ did ช่วยในรูปปฏิเสธ",
     "ถูก — didn't finish ถูกต้องครบทุกส่วน"] },

{ id:"en146", t:"4.3 ฝึกจับผิดประโยค", d:"hard",
  q:"Which sentence with a time clause has NO mistake?",
  c:["When I arrive, I will text you.","When I will arrive, I will text you.","When I arrive, I text you because I will be busy.","When I will arrive, I text you."],
  a:0,
  w:"อนุประโยคที่ขึ้นต้นด้วย when ใช้ Present Simple ส่วนประโยคหลักใช้ will + verb 1",
  e:["ถูก — arrive ในอนุประโยค และ will text ในประโยคหลัก ถูกต้องตามแบบแผน",
     "ผิด — ห้ามใช้ will ในอนุประโยคหลัง when",
     "ผิด — ประโยคหลักควรใช้ will text เพื่อให้ตรงแบบแผน",
     "ผิด — ผิดทั้งสองส่วน"] },

{ id:"en147", t:"4.3 ฝึกจับผิดประโยค", d:"medium",
  q:"Which Past Continuous sentence has a mistake?",
  c:["They were watching a movie at nine.","We was playing in the garden.","I was reading when he called.","She was cooking dinner last night."],
  a:1,
  w:"We เป็นพหูพจน์ จึงต้องใช้ were ไม่ใช่ was",
  e:["ผิด — ข้อนี้ถูกต้อง They + were",
     "ถูก — เป็นข้อที่ผิด ต้องเป็น We were playing in the garden.",
     "ผิด — ข้อนี้ถูกต้อง I + was และ called เป็นเหตุการณ์แทรก",
     "ผิด — ข้อนี้ถูกต้อง She + was"] },

{ id:"en148", t:"4.3 ฝึกจับผิดประโยค", d:"hard",
  q:"Which \"be going to\" sentence has a mistake?",
  c:["I am going to buy a new phone next month.","They are going to move to Bangkok.","He is going to studies engineering.","We are going to have a meeting at ten."],
  a:2,
  w:"หลัง going to ต้องเป็นกริยาช่อง 1 รูปเปล่า ไม่เติม s ตามประธาน",
  e:["ผิด — ข้อนี้ถูกต้องครบทุกส่วน",
     "ผิด — ข้อนี้ถูกต้องครบทุกส่วน",
     "ถูก — เป็นข้อที่ผิด ต้องเป็น He is going to study engineering.",
     "ผิด — ข้อนี้ถูกต้องครบทุกส่วน"] },

{ id:"en149", t:"4.3 ฝึกจับผิดประโยค", d:"medium",
  q:"Which sentence mixes a tense with the wrong time expression?",
  c:["I visited Japan last summer.","I visited Japan in 2019.","I have visited Japan twice.","I have visited Japan in 2019."],
  a:3,
  w:"Present Perfect ใช้กับคำบอกเวลาอดีตที่ระบุชัดเจนอย่าง in 2019 ไม่ได้ ต้องเปลี่ยนเป็น Past Simple",
  e:["ผิด — ข้อนี้ถูกต้อง visited + last summer เข้าคู่กัน",
     "ผิด — ข้อนี้ถูกต้อง visited + in 2019 เข้าคู่กัน",
     "ผิด — ข้อนี้ถูกต้อง twice ไม่ได้ระบุเวลาอดีตที่ชัดเจน",
     "ถูก — เป็นข้อที่ผิด ต้องเป็น I visited Japan in 2019."] },

{ id:"en150", t:"4.3 ฝึกจับผิดประโยค", d:"olympiad",
  q:"Find ALL the mistakes: \"Yesterday I was study English when my friend call me, so I will stop and answered the phone.\"",
  c:["มีที่ผิด 1 จุด คือ was study","มีที่ผิด 3 จุด คือ was study · call · will stop","มีที่ผิด 2 จุด คือ was study และ call","ไม่มีที่ผิดเลย"],
  a:1,
  w:"① was study ต้องเป็น was studying เพราะหลัง was ต้องเติม -ing ② call ต้องเป็น called เพราะเป็นเหตุการณ์แทรกในอดีต ③ will stop ต้องเป็น stopped เพราะทั้งประโยคเล่าเหตุการณ์ในอดีต และต้องขนานกับ answered ที่ตามมา",
  e:["ผิด — ยังมีที่ผิดอีกสองจุดคือ call และ will stop",
     "ถูก — ประโยคที่แก้แล้วคือ Yesterday I was studying English when my friend called me, so I stopped and answered the phone.",
     "ผิด — ยังเหลือ will stop ที่เป็นอนาคตอยู่ในประโยคที่เล่าอดีต",
     "ผิด — ประโยคนี้มีที่ผิดถึงสามจุด"] } ];
